import type { ApiInput } from "./api-directory-types";

function api(input: ApiInput): ApiInput {
  return { ...input, updatedAt: input.updatedAt ?? "2026-06-02" };
}

/** Additional catalog entries for /apis — grouped by builder use case. */
export const apiCatalogAdditionInputs: ApiInput[] = [
  // Wallets & Auth
  api({
    slug: "turnkey",
    name: "Turnkey",
    description: "Wallet infrastructure with MPC key management for teams.",
    purpose: "Embedded wallets and secure key management.",
    whatCanYouBuild: ["Embedded wallets", "MPC key management"],
    popularRecipes: ["Wallet login system", "Trading platform"],
    categories: ["wallets", "authentication", "infrastructure"],
    tags: ["Embedded Wallets", "MPC", "Wallet Login"],
    ecosystems: ["Ethereum", "Base", "Solana", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.turnkey.com",
    links: [
      { label: "Website", url: "https://www.turnkey.com" },
      { label: "Documentation", url: "https://docs.turnkey.com" },
    ],
    docsUrl: "https://docs.turnkey.com",
    toolType: "platform",
  }),
  api({
    slug: "dynamic",
    name: "Dynamic",
    description: "Wallet and auth SDK for multi-wallet login and gated dapp access.",
    purpose: "Wallet connection and authentication for Web3 apps.",
    whatCanYouBuild: ["Multi-wallet login", "Gated dapp access"],
    popularRecipes: ["Wallet login system", "NFT marketplace"],
    relatedApis: [{ slug: "privy", name: "Privy" }, { slug: "turnkey", name: "Turnkey" }],
    categories: ["authentication", "wallets"],
    tags: ["Wallet Login", "Embedded Wallets", "Social Login"],
    ecosystems: ["Ethereum", "Base", "Solana", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.dynamic.xyz",
    links: [
      { label: "Website", url: "https://www.dynamic.xyz" },
      { label: "Documentation", url: "https://docs.dynamic.xyz" },
    ],
    docsUrl: "https://docs.dynamic.xyz",
    toolType: "sdk",
  }),
  api({
    slug: "capsule",
    name: "Capsule",
    description: "Embedded wallet SDK for in-app wallets and gasless UX.",
    purpose: "User-friendly embedded wallets inside your application.",
    whatCanYouBuild: ["In-app wallets", "Gasless UX"],
    popularRecipes: ["SocialFi app", "NFT marketplace"],
    categories: ["wallets", "authentication"],
    tags: ["Embedded Wallets", "Account Abstraction"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://usecapsule.com",
    links: [
      { label: "Website", url: "https://usecapsule.com" },
      { label: "Documentation", url: "https://docs.usecapsule.com" },
    ],
    toolType: "sdk",
  }),
  api({
    slug: "openfort",
    name: "Openfort",
    description: "Game-focused wallet infrastructure with session keys.",
    purpose: "In-game wallets and frictionless player onboarding.",
    whatCanYouBuild: ["In-game wallets", "Session keys"],
    popularRecipes: ["Gaming wallet", "NFT marketplace"],
    categories: ["wallets", "gaming", "authentication"],
    tags: ["Embedded Wallets", "Account Abstraction"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.openfort.xyz",
    links: [
      { label: "Website", url: "https://www.openfort.xyz" },
      { label: "Documentation", url: "https://www.openfort.xyz/docs" },
    ],
    toolType: "platform",
  }),

  // Blockchain Data & Indexing
  api({
    slug: "envio",
    name: "Envio",
    description: "Fast multichain indexer for custom pipelines and live events.",
    purpose: "High-performance blockchain indexing.",
    whatCanYouBuild: ["Custom indexers", "Real-time event tracking"],
    popularRecipes: ["DeFi dashboard", "Trading platform"],
    categories: ["data", "infrastructure"],
    tags: ["Indexing", "Analytics"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/enviodev",
    url: "https://envio.dev",
    links: [
      { label: "Website", url: "https://envio.dev" },
      { label: "Documentation", url: "https://docs.envio.dev" },
    ],
    docsUrl: "https://docs.envio.dev",
    toolType: "platform",
  }),
  api({
    slug: "goldsky",
    name: "Goldsky",
    description: "Subgraph hosting and mirror pipelines for live on-chain data.",
    purpose: "Real-time blockchain data mirrors and subgraphs.",
    whatCanYouBuild: ["Live dashboards", "On-chain analytics"],
    popularRecipes: ["DeFi dashboard", "Token launch analytics"],
    relatedApis: [{ slug: "the-graph", name: "The Graph" }],
    categories: ["data", "infrastructure", "analytics"],
    tags: ["Indexing", "Analytics"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://goldsky.com",
    links: [
      { label: "Website", url: "https://goldsky.com" },
      { label: "Documentation", url: "https://docs.goldsky.com" },
    ],
    docsUrl: "https://docs.goldsky.com",
    toolType: "platform",
  }),
  api({
    slug: "subsquid",
    name: "SQD",
    description: "Decentralized data lake for historical on-chain queries.",
    purpose: "Large-scale blockchain data indexing and analytics.",
    whatCanYouBuild: ["Historical queries", "DeFi analytics"],
    popularRecipes: ["DeFi dashboard", "Trading bot"],
    categories: ["data", "analytics", "infrastructure"],
    tags: ["Indexing", "Analytics", "Market Data"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/subsquid",
    url: "https://sqd.dev",
    links: [
      { label: "Website", url: "https://sqd.dev" },
      { label: "Documentation", url: "https://docs.sqd.dev" },
    ],
    toolType: "platform",
  }),
  api({
    slug: "ponder",
    name: "Ponder",
    description: "Local-first indexing framework for Ethereum app development.",
    purpose: "Fast local indexers during development and production.",
    whatCanYouBuild: ["Local dev indexers", "NFT activity feeds"],
    popularRecipes: ["NFT marketplace", "DeFi dashboard"],
    categories: ["data", "infrastructure"],
    tags: ["Indexing"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ponder-sh/ponder",
    url: "https://ponder.sh",
    links: [
      { label: "Website", url: "https://ponder.sh" },
      { label: "Documentation", url: "https://ponder.sh/docs" },
    ],
    docsUrl: "https://ponder.sh/docs",
    toolType: "sdk",
  }),
  api({
    slug: "quicknode",
    name: "QuickNode",
    description: "Multichain node provider with Streams for real-time webhooks.",
    purpose: "RPC infrastructure and real-time blockchain events.",
    whatCanYouBuild: ["Webhook alerts", "Transaction monitors"],
    popularRecipes: ["Trading bot", "DeFi dashboard"],
    relatedApis: [{ slug: "alchemy", name: "Alchemy" }],
    categories: ["infrastructure", "data"],
    tags: ["RPC", "Indexing", "Market Data"],
    ecosystems: ["Ethereum", "Base", "Solana", "Arbitrum", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.quicknode.com",
    links: [
      { label: "Website", url: "https://www.quicknode.com" },
      { label: "Documentation", url: "https://www.quicknode.com/docs" },
    ],
    docsUrl: "https://www.quicknode.com/docs",
    toolType: "platform",
  }),

  // RPC & Node Infra
  api({
    slug: "ankr",
    name: "Ankr",
    description: "Multichain RPC and staking infrastructure for dapps.",
    purpose: "Public and premium RPC endpoints across chains.",
    whatCanYouBuild: ["Multichain dapps", "Public RPC endpoints"],
    popularRecipes: ["DeFi dashboard", "Wallet login system"],
    relatedApis: [{ slug: "alchemy", name: "Alchemy" }],
    categories: ["infrastructure"],
    tags: ["RPC"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Avalanche", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.ankr.com",
    links: [
      { label: "Website", url: "https://www.ankr.com" },
      { label: "RPC Docs", url: "https://www.ankr.com/docs/rpc-service/" },
    ],
    toolType: "platform",
  }),
  api({
    slug: "blast-api",
    name: "Blast API",
    description: "Free-tier multichain RPC for low-latency applications.",
    purpose: "Cost-effective RPC for bots and high-throughput dapps.",
    whatCanYouBuild: ["Low-latency dapps", "Bot infrastructure"],
    popularRecipes: ["Trading bot", "Market maker bot"],
    categories: ["infrastructure"],
    tags: ["RPC"],
    ecosystems: ["Ethereum", "Polygon", "Arbitrum", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://blastapi.io",
    links: [
      { label: "Website", url: "https://blastapi.io" },
      { label: "Documentation", url: "https://docs.blastapi.io" },
    ],
    docsUrl: "https://docs.blastapi.io",
    toolType: "api",
  }),
  api({
    slug: "tenderly",
    name: "Tenderly",
    description: "Transaction simulation, debugging, and monitoring for EVM chains.",
    purpose: "Safer contract interactions via simulation and alerts.",
    whatCanYouBuild: ["Transaction simulators", "Gas profilers"],
    popularRecipes: ["DeFi dashboard", "Trading platform"],
    categories: ["infrastructure", "analytics"],
    tags: ["RPC", "Analytics"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Polygon"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://tenderly.co",
    links: [
      { label: "Website", url: "https://tenderly.co" },
      { label: "Documentation", url: "https://docs.tenderly.co" },
    ],
    docsUrl: "https://docs.tenderly.co",
    toolType: "platform",
  }),
  api({
    slug: "chainstack",
    name: "Chainstack",
    description: "Managed blockchain nodes and dedicated RPC endpoints.",
    purpose: "Reliable node infrastructure for production workloads.",
    whatCanYouBuild: ["Dedicated nodes", "Private RPC endpoints"],
    popularRecipes: ["Trading platform", "DeFi dashboard"],
    relatedApis: [{ slug: "alchemy", name: "Alchemy" }],
    categories: ["infrastructure"],
    tags: ["RPC"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Avalanche", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://chainstack.com",
    links: [
      { label: "Website", url: "https://chainstack.com" },
      { label: "Documentation", url: "https://docs.chainstack.com" },
    ],
    docsUrl: "https://docs.chainstack.com",
    toolType: "platform",
  }),

  // Smart Contracts & Dev Tools
  api({
    slug: "foundry",
    name: "Foundry",
    description: "Blazing fast Solidity toolkit for testing and deployment.",
    purpose: "Smart contract development and fuzz testing.",
    whatCanYouBuild: ["Contract test suites", "Fuzz testing"],
    popularRecipes: ["DeFi protocol launch", "Token launch"],
    categories: ["infrastructure"],
    tags: ["Hackathons"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/foundry-rs/foundry",
    url: "https://book.getfoundry.sh",
    links: [
      { label: "Book", url: "https://book.getfoundry.sh" },
      { label: "GitHub", url: "https://github.com/foundry-rs/foundry" },
    ],
    toolType: "sdk",
  }),
  api({
    slug: "hardhat",
    name: "Hardhat",
    description: "Ethereum development environment for local chains and scripts.",
    purpose: "Compile, test, and deploy smart contracts.",
    whatCanYouBuild: ["Local dev chains", "Deployment scripts"],
    popularRecipes: ["DeFi protocol launch", "NFT marketplace"],
    categories: ["infrastructure"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/NomicFoundation/hardhat",
    url: "https://hardhat.org",
    links: [
      { label: "Website", url: "https://hardhat.org" },
      { label: "Documentation", url: "https://hardhat.org/docs" },
    ],
    docsUrl: "https://hardhat.org/docs",
    toolType: "sdk",
  }),
  api({
    slug: "openzeppelin",
    name: "OpenZeppelin",
    description: "Audited smart contract libraries and security tooling.",
    purpose: "Standard implementations for tokens, access control, and DAOs.",
    whatCanYouBuild: ["ERC20/721 tokens", "DAO contracts"],
    popularRecipes: ["DeFi protocol launch", "Governance portal"],
    categories: ["infrastructure", "security"],
    tags: ["Hackathons"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/OpenZeppelin/openzeppelin-contracts",
    url: "https://openzeppelin.com",
    links: [
      { label: "Website", url: "https://openzeppelin.com" },
      { label: "Contracts", url: "https://docs.openzeppelin.com/contracts" },
    ],
    docsUrl: "https://docs.openzeppelin.com/contracts",
    toolType: "sdk",
  }),
  api({
    slug: "remix",
    name: "Remix IDE",
    description: "Browser-based Solidity IDE for rapid prototyping.",
    purpose: "Write, compile, and deploy contracts in the browser.",
    whatCanYouBuild: ["Quick prototypes", "Contract audits prep"],
    popularRecipes: ["Token launch", "DeFi protocol launch"],
    categories: ["infrastructure"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ethereum/remix-project",
    url: "https://remix.ethereum.org",
    links: [
      { label: "IDE", url: "https://remix.ethereum.org" },
      { label: "Documentation", url: "https://remix-ide.readthedocs.io" },
    ],
    toolType: "platform",
  }),

  // AI & Agents
  api({
    slug: "coinbase-agentkit",
    name: "Coinbase AgentKit",
    description: "Toolkit for building AI agents with wallet and onchain actions.",
    purpose: "Autonomous agents that can transact onchain.",
    whatCanYouBuild: ["Autonomous DeFi agents", "Wallet-enabled bots"],
    popularRecipes: ["AI agent", "Trading bot"],
    categories: ["ai", "wallets", "infrastructure"],
    tags: ["AI Agents", "Trading Bots"],
    ecosystems: ["Base", "Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/coinbase/agentkit",
    url: "https://github.com/coinbase/agentkit",
    links: [
      { label: "GitHub", url: "https://github.com/coinbase/agentkit" },
      { label: "Documentation", url: "https://github.com/coinbase/agentkit#readme" },
    ],
    toolType: "sdk",
  }),
  api({
    slug: "eliza",
    name: "Eliza",
    description: "Open agent framework for AI assistants and onchain automation.",
    purpose: "Composable agents for social and trading workflows.",
    whatCanYouBuild: ["AI trading bots", "On-chain assistants"],
    popularRecipes: ["AI agent", "Trading bot"],
    relatedApis: [{ slug: "coinbase-agentkit", name: "Coinbase AgentKit" }],
    categories: ["ai", "infrastructure"],
    tags: ["AI Agents", "Trading Bots"],
    ecosystems: ["Ethereum", "Solana", "Base", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/elizaOS/eliza",
    url: "https://github.com/elizaOS/eliza",
    links: [
      { label: "GitHub", url: "https://github.com/elizaOS/eliza" },
      { label: "Documentation", url: "https://elizaos.ai" },
    ],
    toolType: "sdk",
  }),
  api({
    slug: "gaia",
    name: "Gaia",
    description: "Decentralized AI network for private nodes and agent backends.",
    purpose: "Run AI workloads on decentralized infrastructure.",
    whatCanYouBuild: ["Private AI nodes", "Agent backends"],
    popularRecipes: ["AI agent", "Support bot"],
    categories: ["ai", "infrastructure"],
    tags: ["AI Agents"],
    ecosystems: ["Chain-agnostic"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.gaianet.ai",
    links: [
      { label: "Website", url: "https://www.gaianet.ai" },
      { label: "Documentation", url: "https://docs.gaianet.ai" },
    ],
    toolType: "platform",
  }),

  // Onramp & Payments
  api({
    slug: "transak",
    name: "Transak",
    description: "Fiat onramp API for buy-crypto flows and NFT checkout.",
    purpose: "Embed fiat-to-crypto purchases in your app.",
    whatCanYouBuild: ["Buy crypto flows", "NFT checkout"],
    popularRecipes: ["Crypto neobank", "NFT marketplace"],
    categories: ["payments"],
    tags: ["On/Off Ramp", "Payments"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://transak.com",
    links: [
      { label: "Website", url: "https://transak.com" },
      { label: "Documentation", url: "https://docs.transak.com" },
    ],
    docsUrl: "https://docs.transak.com",
    toolType: "api",
  }),
  api({
    slug: "moonpay",
    name: "MoonPay",
    description: "Global crypto onramp for fiat gateways and token purchases.",
    purpose: "Fiat payments into crypto wallets and apps.",
    whatCanYouBuild: ["Fiat gateways", "Token purchases"],
    popularRecipes: ["Crypto neobank", "NFT marketplace"],
    categories: ["payments"],
    tags: ["On/Off Ramp", "Payments"],
    ecosystems: ["Ethereum", "Base", "Solana", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.moonpay.com",
    links: [
      { label: "Website", url: "https://www.moonpay.com" },
      { label: "Documentation", url: "https://dev.moonpay.com" },
    ],
    docsUrl: "https://dev.moonpay.com",
    toolType: "api",
  }),
  api({
    slug: "request-network",
    name: "Request Network",
    description: "Crypto invoicing and payment requests onchain.",
    purpose: "Invoice, payroll, and B2B crypto payments.",
    whatCanYouBuild: ["Crypto payroll", "Invoice financing"],
    popularRecipes: ["Payroll app", "Treasury management"],
    categories: ["payments", "banking"],
    tags: ["Payments", "Payroll", "Stablecoins"],
    ecosystems: ["Ethereum", "Polygon", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/RequestNetwork",
    url: "https://request.network",
    links: [
      { label: "Website", url: "https://request.network" },
      { label: "Documentation", url: "https://docs.request.network" },
    ],
    docsUrl: "https://docs.request.network",
    toolType: "protocol",
  }),

  // Identity & Reputation
  api({
    slug: "gitcoin-passport",
    name: "Gitcoin Passport",
    description: "Identity scoring for sybil resistance and fair airdrops.",
    purpose: "Verify humans and reputation signals in Web3.",
    whatCanYouBuild: ["Sybil resistance", "Airdrop gating"],
    popularRecipes: ["Governance portal", "SocialFi app"],
    categories: ["identity", "security"],
    tags: ["KYC"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/passportxyz",
    url: "https://passport.gitcoin.co",
    links: [
      { label: "Website", url: "https://passport.gitcoin.co" },
      { label: "Documentation", url: "https://docs.passport.xyz" },
    ],
    docsUrl: "https://docs.passport.xyz",
    toolType: "platform",
  }),
  api({
    slug: "ceramic",
    name: "Ceramic",
    description: "Decentralized data network for portable user profiles.",
    purpose: "Composable identity and reputation data.",
    whatCanYouBuild: ["User profiles", "Portable reputation"],
    popularRecipes: ["SocialFi app", "Governance portal"],
    categories: ["identity", "data"],
    tags: ["Social Login"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ceramicnetwork",
    url: "https://ceramic.network",
    links: [
      { label: "Website", url: "https://ceramic.network" },
      { label: "Documentation", url: "https://developers.ceramic.network" },
    ],
    docsUrl: "https://developers.ceramic.network",
    toolType: "protocol",
  }),
  api({
    slug: "ens",
    name: "ENS",
    description: "Ethereum Name Service for human-readable onchain identity.",
    purpose: "Name resolution and decentralized profiles.",
    whatCanYouBuild: ["Human-readable addresses", "On-chain profiles"],
    popularRecipes: ["Wallet login system", "SocialFi app"],
    categories: ["identity", "infrastructure"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: true,
    grantInfo: "ENS ecosystem grants support integrations and public goods.",
    githubUrl: "https://github.com/ensdomains",
    url: "https://ens.domains",
    links: [
      { label: "Website", url: "https://ens.domains" },
      { label: "Documentation", url: "https://docs.ens.domains" },
    ],
    docsUrl: "https://docs.ens.domains",
    toolType: "protocol",
  }),

  // Storage
  api({
    slug: "ipfs",
    name: "IPFS",
    description: "Decentralized storage protocol for content-addressed files.",
    purpose: "Host NFT metadata and static assets offchain.",
    whatCanYouBuild: ["NFT metadata", "Decentralized hosting"],
    popularRecipes: ["NFT marketplace", "SocialFi app"],
    categories: ["infrastructure", "data"],
    ecosystems: ["Chain-agnostic"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ipfs/kubo",
    url: "https://ipfs.tech",
    links: [
      { label: "Website", url: "https://ipfs.tech" },
      { label: "Documentation", url: "https://docs.ipfs.tech" },
    ],
    docsUrl: "https://docs.ipfs.tech",
    toolType: "protocol",
  }),
  api({
    slug: "arweave",
    name: "Arweave",
    description: "Permanent decentralized storage for immutable media and docs.",
    purpose: "Store data with long-term persistence guarantees.",
    whatCanYouBuild: ["Immutable docs", "On-chain media"],
    popularRecipes: ["NFT marketplace", "Governance portal"],
    categories: ["infrastructure", "data"],
    ecosystems: ["Chain-agnostic"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ArweaveTeam/arweave",
    url: "https://arweave.org",
    links: [
      { label: "Website", url: "https://arweave.org" },
      { label: "Documentation", url: "https://docs.arweave.org" },
    ],
    toolType: "protocol",
  }),
  api({
    slug: "lighthouse",
    name: "Lighthouse",
    description: "IPFS and Filecoin storage with encryption for Web3 assets.",
    purpose: "Managed decentralized file storage for dapps.",
    whatCanYouBuild: ["Encrypted file storage", "NFT assets"],
    popularRecipes: ["NFT marketplace", "SocialFi app"],
    relatedApis: [{ slug: "ipfs", name: "IPFS" }],
    categories: ["infrastructure", "data"],
    ecosystems: ["Chain-agnostic"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://lighthouse.storage",
    links: [
      { label: "Website", url: "https://lighthouse.storage" },
      { label: "Documentation", url: "https://docs.lighthouse.storage" },
    ],
    docsUrl: "https://docs.lighthouse.storage",
    toolType: "api",
  }),

  // Cross-chain & Bridges
  api({
    slug: "layerzero",
    name: "LayerZero",
    description: "Omnichain messaging protocol for cross-chain apps.",
    purpose: "Send messages and tokens across chains securely.",
    whatCanYouBuild: ["Cross-chain tokens", "Multichain dapps"],
    popularRecipes: ["DeFi dashboard", "Bridge UI"],
    categories: ["infrastructure"],
    tags: ["Grants"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: true,
    grantInfo: "LayerZero ecosystem funding supports omnichain application development.",
    url: "https://layerzero.network",
    links: [
      { label: "Website", url: "https://layerzero.network" },
      { label: "Documentation", url: "https://docs.layerzero.network" },
    ],
    docsUrl: "https://docs.layerzero.network",
    toolType: "protocol",
  }),
  api({
    slug: "axelar",
    name: "Axelar",
    description: "Cross-chain SDK for bridging assets and interchain dapps.",
    purpose: "General message passing and asset transfers.",
    whatCanYouBuild: ["Bridged assets", "Interchain dapps"],
    popularRecipes: ["DeFi dashboard", "Bridge UI"],
    categories: ["infrastructure"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: true,
    githubUrl: "https://github.com/axelarnetwork",
    url: "https://axelar.network",
    links: [
      { label: "Website", url: "https://axelar.network" },
      { label: "Documentation", url: "https://docs.axelar.dev" },
    ],
    docsUrl: "https://docs.axelar.dev",
    toolType: "protocol",
  }),
  api({
    slug: "wormhole",
    name: "Wormhole",
    description: "Cross-chain bridge SDK for tokens and NFTs.",
    purpose: "Move assets and messages between major chains.",
    whatCanYouBuild: ["Cross-chain NFTs", "Token bridges"],
    popularRecipes: ["NFT marketplace", "Bridge UI"],
    categories: ["infrastructure"],
    ecosystems: ["Ethereum", "Solana", "Base", "Arbitrum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: true,
    githubUrl: "https://github.com/wormhole-foundation",
    url: "https://wormhole.com",
    links: [
      { label: "Website", url: "https://wormhole.com" },
      { label: "Documentation", url: "https://docs.wormhole.com" },
    ],
    docsUrl: "https://docs.wormhole.com",
    toolType: "protocol",
  }),

  // Analytics & Monitoring
  api({
    slug: "defined-fi",
    name: "Defined.fi",
    description: "DEX analytics API for token screeners and trading dashboards.",
    purpose: "Real-time onchain trading and liquidity data.",
    whatCanYouBuild: ["Token screeners", "Trading dashboards"],
    popularRecipes: ["Trading platform", "Trading bot"],
    relatedApis: [{ slug: "dune", name: "Dune Analytics" }],
    categories: ["analytics", "data", "trading"],
    tags: ["Market Data", "Analytics", "Trading API"],
    ecosystems: ["Ethereum", "Base", "Solana", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://defined.fi",
    links: [
      { label: "Website", url: "https://defined.fi" },
      { label: "Documentation", url: "https://docs.defined.fi" },
    ],
    toolType: "api",
  }),
  api({
    slug: "nansen",
    name: "Nansen",
    description: "Wallet intelligence and smart-money analytics for onchain research.",
    purpose: "Labelled wallet data and institutional-grade insights.",
    whatCanYouBuild: ["Smart money trackers", "Wallet profilers"],
    popularRecipes: ["Trading bot", "Portfolio dashboard"],
    relatedApis: [{ slug: "dune", name: "Dune Analytics" }],
    categories: ["analytics", "data"],
    tags: ["Analytics", "Market Data"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: false,
    isFree: false,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.nansen.ai",
    links: [
      { label: "Website", url: "https://www.nansen.ai" },
      { label: "API", url: "https://docs.nansen.ai" },
    ],
    docsUrl: "https://docs.nansen.ai",
    toolType: "api",
  }),
  api({
    slug: "token-terminal",
    name: "Token Terminal",
    description: "Standardized protocol financials and revenue metrics.",
    purpose: "Compare protocol revenue and fundamentals.",
    whatCanYouBuild: ["Revenue dashboards", "Protocol comparisons"],
    popularRecipes: ["DeFi dashboard", "Governance portal"],
    categories: ["analytics", "data"],
    tags: ["Analytics"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://tokenterminal.com",
    links: [
      { label: "Website", url: "https://tokenterminal.com" },
      { label: "Documentation", url: "https://docs.tokenterminal.com" },
    ],
    docsUrl: "https://docs.tokenterminal.com",
    toolType: "api",
  }),

  // Messaging & Social
  api({
    slug: "xmtp",
    name: "XMTP",
    description: "Wallet-to-wallet messaging protocol for encrypted onchain DMs.",
    purpose: "End-to-end encrypted chat between wallet addresses.",
    whatCanYouBuild: ["Encrypted DMs", "In-app chat"],
    popularRecipes: ["Wallet login system", "SocialFi app"],
    categories: ["messaging-social", "infrastructure"],
    tags: ["Messaging", "Wallet Login"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/xmtp",
    url: "https://xmtp.org",
    links: [
      { label: "Website", url: "https://xmtp.org" },
      { label: "Documentation", url: "https://docs.xmtp.org" },
    ],
    docsUrl: "https://docs.xmtp.org",
    toolType: "protocol",
  }),
  api({
    slug: "farcaster",
    name: "Farcaster",
    description: "Decentralized social protocol for feeds, frames, and mini apps.",
    purpose: "Open social graphs and composable social primitives.",
    whatCanYouBuild: ["Mini apps", "Social graphs"],
    popularRecipes: ["SocialFi app", "NFT marketplace"],
    categories: ["messaging-social", "identity"],
    tags: ["Social", "Messaging"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/farcasterxyz",
    url: "https://www.farcaster.xyz",
    links: [
      { label: "Website", url: "https://www.farcaster.xyz" },
      { label: "Documentation", url: "https://docs.farcaster.xyz" },
    ],
    docsUrl: "https://docs.farcaster.xyz",
    toolType: "protocol",
  }),
  api({
    slug: "push-protocol",
    name: "Push Protocol",
    description: "Web3 notification network for wallet alerts and channel broadcasts.",
    purpose: "Onchain and offchain notifications to wallet users.",
    whatCanYouBuild: ["Wallet alerts", "DAO announcements"],
    popularRecipes: ["Governance portal", "DeFi dashboard"],
    categories: ["messaging-social", "infrastructure"],
    tags: ["Notifications", "Messaging"],
    ecosystems: ["Ethereum", "Polygon", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/push-protocol",
    url: "https://push.org",
    links: [
      { label: "Website", url: "https://push.org" },
      { label: "Documentation", url: "https://push.org/docs" },
    ],
    docsUrl: "https://push.org/docs",
    toolType: "protocol",
  }),

  // Oracles & Real World Data
  api({
    slug: "chronicle",
    name: "Chronicle",
    description: "Decentralized oracle network for price feeds and RWA data.",
    purpose: "Transparent, verifiable data for DeFi and real-world assets.",
    whatCanYouBuild: ["Price feeds", "RWA data"],
    popularRecipes: ["DeFi dashboard", "Trading platform"],
    categories: ["oracles-rwa", "data"],
    tags: ["Oracles", "Market Data"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://chroniclelabs.org",
    links: [
      { label: "Website", url: "https://chroniclelabs.org" },
      { label: "Documentation", url: "https://docs.chroniclelabs.org" },
    ],
    toolType: "protocol",
  }),
  api({
    slug: "tellor",
    name: "Tellor",
    description: "Permissionless oracle for custom data feeds and dispute resolution.",
    purpose: "Community-driven data reporting without centralized operators.",
    whatCanYouBuild: ["Custom data feeds", "Dispute systems"],
    popularRecipes: ["DeFi dashboard", "Trading bot"],
    categories: ["oracles-rwa", "data"],
    tags: ["Oracles"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/tellor-io",
    url: "https://tellor.io",
    links: [
      { label: "Website", url: "https://tellor.io" },
      { label: "Documentation", url: "https://docs.tellor.io" },
    ],
    docsUrl: "https://docs.tellor.io",
    toolType: "protocol",
  }),
  api({
    slug: "api3",
    name: "API3",
    description: "First-party oracle network with dAPI feeds and Airnode integrations.",
    purpose: "Direct API-to-smart-contract data without middlemen.",
    whatCanYouBuild: ["dAPI feeds", "Airnode integrations"],
    popularRecipes: ["DeFi dashboard", "Trading platform"],
    categories: ["oracles-rwa", "data", "infrastructure"],
    tags: ["Oracles", "Market Data"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/api3dao",
    url: "https://api3.org",
    links: [
      { label: "Website", url: "https://api3.org" },
      { label: "Documentation", url: "https://docs.api3.org" },
    ],
    docsUrl: "https://docs.api3.org",
    toolType: "protocol",
  }),

  // DeFi Primitives
  api({
    slug: "uniswap-sdk",
    name: "Uniswap SDK",
    description: "Official SDK for Uniswap swaps, routing, and liquidity management.",
    purpose: "Programmatic access to Uniswap pools and swap logic.",
    whatCanYouBuild: ["Token swaps", "Liquidity managers"],
    popularRecipes: ["DeFi dashboard", "Trading platform"],
    categories: ["defi-primitives", "trading"],
    tags: ["DeFi", "Trading API"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/Uniswap",
    url: "https://docs.uniswap.org/sdk/v4/overview",
    links: [
      { label: "SDK Docs", url: "https://docs.uniswap.org/sdk/v4/overview" },
      { label: "GitHub", url: "https://github.com/Uniswap" },
    ],
    docsUrl: "https://docs.uniswap.org/sdk/v4/overview",
    toolType: "sdk",
  }),
  api({
    slug: "aave-sdk",
    name: "Aave SDK",
    description: "SDK and APIs for Aave lending markets and position management.",
    purpose: "Borrow, lend, and compose yield strategies on Aave.",
    whatCanYouBuild: ["Borrow/lend apps", "Yield aggregators"],
    popularRecipes: ["DeFi dashboard", "Portfolio dashboard"],
    categories: ["defi-primitives", "trading"],
    tags: ["DeFi", "Lending"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/aave",
    url: "https://aave.com/docs",
    links: [
      { label: "Documentation", url: "https://aave.com/docs" },
      { label: "GitHub", url: "https://github.com/aave" },
    ],
    docsUrl: "https://aave.com/docs",
    toolType: "sdk",
  }),
  api({
    slug: "zerox-protocol",
    name: "0x Protocol",
    description: "Swap aggregator protocol and APIs for DEX liquidity.",
    purpose: "Best-price swaps across decentralized liquidity sources.",
    whatCanYouBuild: ["DEX aggregators", "Trading APIs"],
    popularRecipes: ["Trading platform", "DeFi dashboard"],
    categories: ["defi-primitives", "trading"],
    tags: ["DeFi", "Trading API"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/0xProject",
    url: "https://0x.org",
    links: [
      { label: "Website", url: "https://0x.org" },
      { label: "API Docs", url: "https://0x.org/docs/api" },
    ],
    docsUrl: "https://0x.org/docs/api",
    toolType: "protocol",
  }),

  // Developer Experience
  api({
    slug: "scaffold-eth",
    name: "Scaffold-ETH",
    description: "Full-stack Ethereum starter kit for rapid dapp prototyping.",
    purpose: "Batteries-included templates for contracts, frontend, and deploy.",
    whatCanYouBuild: ["Dapp prototypes", "Hackathon starters"],
    popularRecipes: ["Wallet login system", "NFT marketplace"],
    categories: ["developer-experience", "infrastructure"],
    tags: ["Wallet Login"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/scaffold-eth/scaffold-eth-2",
    url: "https://scaffoldeth.io",
    links: [
      { label: "Website", url: "https://scaffoldeth.io" },
      { label: "Documentation", url: "https://docs.scaffoldeth.io" },
    ],
    docsUrl: "https://docs.scaffoldeth.io",
    toolType: "sdk",
  }),
  api({
    slug: "wagmi",
    name: "Wagmi",
    description: "React hooks for Ethereum wallets, contracts, and chain state.",
    purpose: "Type-safe React integrations for Web3 frontends.",
    whatCanYouBuild: ["Wallet UIs", "Contract interactions"],
    popularRecipes: ["Wallet login system", "DeFi dashboard"],
    relatedApis: [{ slug: "viem", name: "Viem" }],
    categories: ["developer-experience", "wallets"],
    tags: ["Wallet Login"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/wevm/wagmi",
    url: "https://wagmi.sh",
    links: [
      { label: "Website", url: "https://wagmi.sh" },
      { label: "Documentation", url: "https://wagmi.sh/react/getting-started" },
    ],
    docsUrl: "https://wagmi.sh/react/getting-started",
    toolType: "sdk",
  }),
  api({
    slug: "viem",
    name: "Viem",
    description: "TypeScript Ethereum client for RPC, contracts, and transactions.",
    purpose: "Lightweight, typed interface to Ethereum nodes and ABIs.",
    whatCanYouBuild: ["Contract calls", "Raw tx builders"],
    popularRecipes: ["Trading bot", "DeFi dashboard"],
    relatedApis: [{ slug: "wagmi", name: "Wagmi" }],
    categories: ["developer-experience", "infrastructure"],
    tags: ["RPC"],
    ecosystems: ["Ethereum", "Base", "Arbitrum", "Optimism", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/wevm/viem",
    url: "https://viem.sh",
    links: [
      { label: "Website", url: "https://viem.sh" },
      { label: "Documentation", url: "https://viem.sh/docs/getting-started" },
    ],
    docsUrl: "https://viem.sh/docs/getting-started",
    toolType: "sdk",
  }),

  // Gasless & Paymaster
  api({
    slug: "pimlico",
    name: "Pimlico",
    description: "ERC-4337 infrastructure for bundlers, paymasters, and smart accounts.",
    purpose: "Sponsored gas and account-abstraction operations at scale.",
    whatCanYouBuild: ["Gasless transactions", "Smart accounts"],
    popularRecipes: ["Wallet login system", "SocialFi app"],
    categories: ["gasless-paymaster", "infrastructure"],
    tags: ["Gasless", "Account Abstraction"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.pimlico.io",
    links: [
      { label: "Website", url: "https://www.pimlico.io" },
      { label: "Documentation", url: "https://docs.pimlico.io" },
    ],
    docsUrl: "https://docs.pimlico.io",
    toolType: "platform",
  }),
  api({
    slug: "zerodev",
    name: "ZeroDev",
    description: "Account abstraction toolkit with session keys and sponsored gas.",
    purpose: "Smart accounts and gasless UX for consumer dapps.",
    whatCanYouBuild: ["Session keys", "Sponsored gas"],
    popularRecipes: ["Gaming wallet", "NFT marketplace"],
    relatedApis: [{ slug: "pimlico", name: "Pimlico" }, { slug: "biconomy", name: "Biconomy" }],
    categories: ["gasless-paymaster", "wallets"],
    tags: ["Gasless", "Account Abstraction"],
    ecosystems: ["Ethereum", "Base", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://zerodev.app",
    links: [
      { label: "Website", url: "https://zerodev.app" },
      { label: "Documentation", url: "https://docs.zerodev.app" },
    ],
    docsUrl: "https://docs.zerodev.app",
    toolType: "platform",
  }),
  api({
    slug: "biconomy",
    name: "Biconomy",
    description: "Transaction infrastructure for gasless UX and bundler APIs.",
    purpose: "Paymasters and meta-transactions for mainstream onboarding.",
    whatCanYouBuild: ["Gasless UX", "Bundler APIs"],
    popularRecipes: ["Wallet login system", "SocialFi app"],
    categories: ["gasless-paymaster", "infrastructure"],
    tags: ["Gasless", "Account Abstraction"],
    ecosystems: ["Ethereum", "Base", "Polygon", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.biconomy.io",
    links: [
      { label: "Website", url: "https://www.biconomy.io" },
      { label: "Documentation", url: "https://docs.biconomy.io" },
    ],
    docsUrl: "https://docs.biconomy.io",
    toolType: "platform",
  }),

  // Privacy
  api({
    slug: "aztec",
    name: "Aztec",
    description: "Private smart contracts and shielded execution on Ethereum.",
    purpose: "Confidential transfers and private DeFi without exposing balances.",
    whatCanYouBuild: ["Private transfers", "Shielded DeFi"],
    popularRecipes: ["DeFi dashboard", "Wallet login system"],
    categories: ["privacy", "security"],
    tags: ["Privacy"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: true,
    githubUrl: "https://github.com/AztecProtocol",
    url: "https://aztec.network",
    links: [
      { label: "Website", url: "https://aztec.network" },
      { label: "Documentation", url: "https://docs.aztec.network" },
    ],
    docsUrl: "https://docs.aztec.network",
    toolType: "protocol",
  }),
  api({
    slug: "semaphore",
    name: "Semaphore",
    description: "Zero-knowledge groups for anonymous signaling and private identity.",
    purpose: "Prove membership without revealing which member you are.",
    whatCanYouBuild: ["Anonymous voting", "Private identity"],
    popularRecipes: ["Governance portal", "Wallet login system"],
    categories: ["privacy", "identity"],
    tags: ["Privacy"],
    ecosystems: ["Ethereum", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/semaphore-protocol",
    url: "https://semaphore.pse.dev",
    links: [
      { label: "Website", url: "https://semaphore.pse.dev" },
      { label: "Documentation", url: "https://docs.semaphore.pse.dev" },
    ],
    docsUrl: "https://docs.semaphore.pse.dev",
    toolType: "sdk",
  }),

  // Solana
  api({
    slug: "helius",
    name: "Helius",
    description: "Solana RPC, webhooks, and enriched transaction APIs.",
    purpose: "High-performance Solana infrastructure and real-time events.",
    whatCanYouBuild: ["NFT indexing", "Real-time transaction alerts"],
    popularRecipes: ["NFT marketplace", "Portfolio dashboard"],
    categories: ["infrastructure", "data"],
    tags: ["RPC", "Indexing", "NFT"],
    ecosystems: ["Solana"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.helius.dev",
    links: [
      { label: "Website", url: "https://www.helius.dev" },
      { label: "Documentation", url: "https://docs.helius.dev" },
    ],
    docsUrl: "https://docs.helius.dev",
    toolType: "platform",
  }),
  api({
    slug: "metaplex",
    name: "Metaplex",
    description: "NFT standard and SDK for digital assets on Solana.",
    purpose: "Mint, manage, and sell NFTs with Solana-native tooling.",
    whatCanYouBuild: ["NFT minting", "Digital asset marketplaces"],
    popularRecipes: ["NFT marketplace", "Gaming wallet"],
    categories: ["data", "gaming"],
    tags: ["NFT"],
    ecosystems: ["Solana"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/metaplex-foundation",
    url: "https://www.metaplex.com",
    links: [
      { label: "Website", url: "https://www.metaplex.com" },
      { label: "Documentation", url: "https://developers.metaplex.com" },
    ],
    docsUrl: "https://developers.metaplex.com",
    toolType: "sdk",
  }),
  api({
    slug: "jupiter-sdk",
    name: "Jupiter SDK",
    description: "Solana swap aggregator SDK for routing and DCA strategies.",
    purpose: "Best-route swaps and programmatic trading on Solana.",
    whatCanYouBuild: ["Token swaps", "DCA bots"],
    popularRecipes: ["Trading bot", "DeFi dashboard"],
    categories: ["defi-primitives", "trading"],
    tags: ["DeFi", "Trading API"],
    ecosystems: ["Solana"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/jup-ag",
    url: "https://station.jup.ag/docs",
    links: [
      { label: "Documentation", url: "https://station.jup.ag/docs" },
      { label: "GitHub", url: "https://github.com/jup-ag" },
    ],
    docsUrl: "https://station.jup.ag/docs",
    toolType: "sdk",
  }),
  api({
    slug: "anchor",
    name: "Anchor",
    description: "Solana development framework for programs, tests, and IDLs.",
    purpose: "Standard toolkit for building and testing Solana smart contracts.",
    whatCanYouBuild: ["Smart contract dev", "Program testing"],
    popularRecipes: ["NFT marketplace", "Trading bot"],
    categories: ["developer-experience", "infrastructure"],
    tags: ["RPC"],
    ecosystems: ["Solana"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/coral-xyz/anchor",
    url: "https://www.anchor-lang.com",
    links: [
      { label: "Website", url: "https://www.anchor-lang.com" },
      { label: "Documentation", url: "https://www.anchor-lang.com/docs" },
    ],
    docsUrl: "https://www.anchor-lang.com/docs",
    toolType: "sdk",
  }),
  api({
    slug: "dialect",
    name: "Dialect",
    description: "Solana messaging and notification rails for wallets and apps.",
    purpose: "In-app alerts and programmable messaging on Solana.",
    whatCanYouBuild: ["Wallet notifications", "In-app alerts"],
    popularRecipes: ["SocialFi app", "NFT marketplace"],
    categories: ["messaging-social", "infrastructure"],
    tags: ["Messaging", "Notifications"],
    ecosystems: ["Solana"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.dialect.to",
    links: [
      { label: "Website", url: "https://www.dialect.to" },
      { label: "Documentation", url: "https://docs.dialect.to" },
    ],
    docsUrl: "https://docs.dialect.to",
    toolType: "platform",
  }),
  api({
    slug: "shyft",
    name: "Shyft",
    description: "Solana APIs for transaction parsing and wallet activity feeds.",
    purpose: "Human-readable Solana data without running your own indexer.",
    whatCanYouBuild: ["Transaction parsing", "Wallet activity feeds"],
    popularRecipes: ["Portfolio dashboard", "NFT marketplace"],
    categories: ["data", "analytics"],
    tags: ["Indexing", "Analytics"],
    ecosystems: ["Solana"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://shyft.to",
    links: [
      { label: "Website", url: "https://shyft.to" },
      { label: "Documentation", url: "https://docs.shyft.to" },
    ],
    docsUrl: "https://docs.shyft.to",
    toolType: "api",
  }),

  // Sui
  api({
    slug: "mysten-labs-sdk",
    name: "Mysten Labs SDK",
    description: "Official Sui TypeScript SDK for objects, transactions, and wallets.",
    purpose: "Build object-centric dapps on the Sui network.",
    whatCanYouBuild: ["Object-based dapps", "NFT platforms"],
    popularRecipes: ["NFT marketplace", "Wallet login system"],
    categories: ["developer-experience", "infrastructure"],
    tags: ["NFT"],
    ecosystems: ["Sui"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/MystenLabs/sui",
    url: "https://sdk.mystenlabs.com",
    links: [
      { label: "SDK Docs", url: "https://sdk.mystenlabs.com/typescript" },
      { label: "GitHub", url: "https://github.com/MystenLabs/sui" },
    ],
    docsUrl: "https://sdk.mystenlabs.com/typescript",
    toolType: "sdk",
  }),
  api({
    slug: "shinami",
    name: "Shinami",
    description: "Sui node infrastructure and gas station for sponsored transactions.",
    purpose: "Managed RPC and gasless wallets on Sui.",
    whatCanYouBuild: ["Gasless txs", "Sponsored wallets"],
    popularRecipes: ["NFT marketplace", "SocialFi app"],
    categories: ["gasless-paymaster", "infrastructure"],
    tags: ["Gasless", "RPC"],
    ecosystems: ["Sui"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://www.shinami.com",
    links: [
      { label: "Website", url: "https://www.shinami.com" },
      { label: "Documentation", url: "https://docs.shinami.com" },
    ],
    docsUrl: "https://docs.shinami.com",
    toolType: "platform",
  }),

  // Aptos
  api({
    slug: "aptos-sdk",
    name: "Aptos SDK",
    description: "Official Aptos SDK for Move contracts, accounts, and transactions.",
    purpose: "Type-safe tooling for Aptos application development.",
    whatCanYouBuild: ["DeFi apps", "Token launchpads"],
    popularRecipes: ["DeFi dashboard", "NFT marketplace"],
    categories: ["developer-experience", "infrastructure"],
    tags: ["DeFi"],
    ecosystems: ["Aptos"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/aptos-labs",
    url: "https://aptos.dev",
    links: [
      { label: "Documentation", url: "https://aptos.dev/build/sdks" },
      { label: "GitHub", url: "https://github.com/aptos-labs" },
    ],
    docsUrl: "https://aptos.dev/build/sdks",
    toolType: "sdk",
  }),
  api({
    slug: "nodit",
    name: "Nodit",
    description: "Multichain RPC and indexing with Aptos-first developer APIs.",
    purpose: "Unified node access and event tracking across chains.",
    whatCanYouBuild: ["Multichain indexing", "Event tracking"],
    popularRecipes: ["DeFi dashboard", "Portfolio dashboard"],
    categories: ["infrastructure", "data"],
    tags: ["RPC", "Indexing"],
    ecosystems: ["Aptos", "Ethereum", "Multi-chain"],
    isOpenSource: false,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    url: "https://nodit.io",
    links: [
      { label: "Website", url: "https://nodit.io" },
      { label: "Documentation", url: "https://docs.nodit.io" },
    ],
    docsUrl: "https://docs.nodit.io",
    toolType: "platform",
  }),

  // Bitcoin / Lightning
  api({
    slug: "lnd",
    name: "LND",
    description: "Lightning Network daemon for channels, invoices, and Bitcoin payments.",
    purpose: "Self-hosted Lightning node software for payment apps.",
    whatCanYouBuild: ["Payment channels", "Bitcoin apps"],
    popularRecipes: ["Payments checkout", "Wallet login system"],
    categories: ["payments", "infrastructure"],
    tags: ["Payments"],
    ecosystems: ["Bitcoin"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/lightningnetwork/lnd",
    url: "https://lightning.engineering",
    links: [
      { label: "Website", url: "https://lightning.engineering" },
      { label: "Documentation", url: "https://docs.lightning.engineering" },
    ],
    docsUrl: "https://docs.lightning.engineering",
    toolType: "protocol",
  }),
  api({
    slug: "alby",
    name: "Alby",
    description: "Lightning wallet API for micropayments and web monetization.",
    purpose: "Bitcoin-native payments in browsers and applications.",
    whatCanYouBuild: ["Micropayments", "Bitcoin web monetization"],
    popularRecipes: ["Payments checkout", "SocialFi app"],
    categories: ["payments", "wallets"],
    tags: ["Payments"],
    ecosystems: ["Bitcoin"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/getAlby",
    url: "https://getalby.com",
    links: [
      { label: "Website", url: "https://getalby.com" },
      { label: "API Docs", url: "https://guides.getalby.com" },
    ],
    docsUrl: "https://guides.getalby.com",
    toolType: "api",
  }),
  api({
    slug: "stacks-sdk",
    name: "Stacks SDK",
    description: "SDK for Bitcoin-anchored smart contracts on the Stacks layer.",
    purpose: "DeFi and NFT logic secured by Bitcoin settlement.",
    whatCanYouBuild: ["DeFi on Bitcoin", "NFTs on Bitcoin"],
    popularRecipes: ["NFT marketplace", "DeFi dashboard"],
    categories: ["developer-experience", "defi-primitives"],
    tags: ["DeFi", "NFT"],
    ecosystems: ["Bitcoin"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/stacks-network",
    url: "https://www.stacks.co",
    links: [
      { label: "Website", url: "https://www.stacks.co" },
      { label: "Documentation", url: "https://docs.stacks.co" },
    ],
    docsUrl: "https://docs.stacks.co",
    toolType: "sdk",
  }),

  // Cosmos
  api({
    slug: "cosmjs",
    name: "CosmJS",
    description: "TypeScript client for Cosmos SDK chains and IBC transfers.",
    purpose: "Query and transact on Cosmos zones from JavaScript apps.",
    whatCanYouBuild: ["IBC dapps", "Chain interactions"],
    popularRecipes: ["DeFi dashboard", "Wallet login system"],
    categories: ["developer-experience", "infrastructure"],
    tags: ["Cross-chain"],
    ecosystems: ["Cosmos"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/cosmos/cosmjs",
    url: "https://cosmos.github.io/cosmjs",
    links: [
      { label: "Documentation", url: "https://cosmos.github.io/cosmjs" },
      { label: "GitHub", url: "https://github.com/cosmos/cosmjs" },
    ],
    docsUrl: "https://cosmos.github.io/cosmjs",
    toolType: "sdk",
  }),
  api({
    slug: "skip-protocol",
    name: "Skip Protocol",
    description: "MEV-aware routing and cross-chain swap infrastructure for Cosmos.",
    purpose: "Optimize swaps and relayer flows across IBC-connected chains.",
    whatCanYouBuild: ["Cross-chain swaps", "Relayer infra"],
    popularRecipes: ["Trading platform", "DeFi dashboard"],
    categories: ["defi-primitives", "infrastructure"],
    tags: ["Cross-chain", "DeFi", "Trading API"],
    ecosystems: ["Cosmos", "Multi-chain"],
    isOpenSource: true,
    isFree: true,
    isFreemium: true,
    hasGrantProgram: false,
    githubUrl: "https://github.com/skip-mev",
    url: "https://skip.money",
    links: [
      { label: "Website", url: "https://skip.money" },
      { label: "Documentation", url: "https://docs.skip.money" },
    ],
    docsUrl: "https://docs.skip.money",
    toolType: "protocol",
  }),

  // TON
  api({
    slug: "ton-sdk",
    name: "TON SDK",
    description: "SDK for The Open Network and Telegram-native mini app payments.",
    purpose: "Build bots and mini apps with TON wallets and payments.",
    whatCanYouBuild: ["Mini app payments", "Bot monetization"],
    popularRecipes: ["Payments checkout", "SocialFi app"],
    categories: ["developer-experience", "payments"],
    tags: ["Payments"],
    ecosystems: ["TON"],
    isOpenSource: true,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: false,
    githubUrl: "https://github.com/ton-org",
    url: "https://ton.org/dev",
    links: [
      { label: "Developer Hub", url: "https://ton.org/dev" },
      { label: "Documentation", url: "https://docs.ton.org" },
    ],
    docsUrl: "https://docs.ton.org",
    toolType: "sdk",
  }),

  api({
    slug: "solana",
    name: "Solana",
    description: "High-performance L1 for scalable consumer and DeFi applications.",
    purpose: "Fast, low-cost transactions for web-scale onchain apps.",
    whatCanYouBuild: ["Consumer dapps", "NFT platforms", "Payments apps"],
    popularRecipes: ["Solana Pay Store", "NFT marketplace"],
    categories: ["infrastructure"],
    tags: ["RPC", "NFT"],
    ecosystems: ["Solana"],
    isOpenSource: false,
    isFree: true,
    isFreemium: false,
    hasGrantProgram: true,
    url: "https://solana.com",
    links: [
      { label: "Website", url: "https://solana.com" },
      { label: "Developer Docs", url: "https://solana.com/developers" },
    ],
    docsUrl: "https://solana.com/developers",
    toolType: "platform",
  }),
];