import { defineGrant } from "./grants-detail-defaults";

export const grantsDirectory = [
  defineGrant({
    slug: "base-builder-program",
    name: "Base Builder Program",
    org: "Coinbase",
    description:
      "Funding for apps, infra and developer tools shipping on Base.",
    overview:
      "Base Builder Program supports teams building consumer apps, DeFi, and infrastructure on Base with rolling applications and milestone-based payouts.",
    ecosystemSlug: "base",
    ecosystemSlugs: ["base"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["solo-builder", "startup", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://base.org/build/grants",
    websiteUrl: "https://base.org/build",
    addedAt: "2026-02-15",
    relatedApiSlugs: ["privy", "alchemy", "dune"],
    relatedRecipeSlugs: ["onchain-commerce-shop", "base-social-mini-app"],
  }),
  defineGrant({
    slug: "alliance-accelerator",
    name: "Alliance Accelerator",
    org: "Alliance DAO",
    description:
      "Accelerator for crypto founders with mentorship, capital, and ecosystem intros.",
    overview:
      "Alliance Accelerator backs early crypto teams with capital, mentorship, and distribution support across DeFi, infra, and consumer apps.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base"],
    fundingRange: "$100K – $500K",
    deadline: "Cohort 12 · Sep 2026",
    deadlineSortOrder: 202609,
    status: "active",
    fundingType: "accelerator",
    fundingStages: ["pre-seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://alliance.xyz",
    websiteUrl: "https://alliance.xyz",
    addedAt: "2026-03-01",
    relatedApiSlugs: ["privy", "alchemy", "walletconnect"],
    relatedRecipeSlugs: ["defi-lending-app", "onchain-commerce-shop"],
  }),
  defineGrant({
    slug: "a16z-crypto-startup-school",
    name: "a16z Crypto Startup School",
    org: "a16z crypto",
    description:
      "Education and accelerator program for founders exploring crypto startup ideas.",
    overview:
      "a16z Crypto Startup School helps founders go from idea to fundable company with lectures, mentorship, and investor access.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "solana"],
    fundingRange: "Program access + network",
    deadline: "Class of 2026 · May 2026",
    deadlineSortOrder: 202605,
    status: "upcoming",
    fundingType: "accelerator",
    fundingTypeLabel: "Education + Accelerator",
    fundingStages: ["idea", "pre-seed"],
    builderTypes: ["solo-builder", "startup", "student"],
    location: "San Francisco + Remote",
    remoteFriendly: true,
    applyUrl: "https://a16zcrypto.com/posts/article/startup-school",
    websiteUrl: "https://a16zcrypto.com",
    addedAt: "2026-04-01",
    relatedApiSlugs: ["privy", "alchemy"],
    relatedRecipeSlugs: ["onchain-agent-demo", "defi-lending-app"],
  }),
  defineGrant({
    slug: "solana-hackathon",
    name: "Solana Hackathon",
    org: "Solana Foundation",
    description:
      "Global hackathon for shipping Solana apps with prizes and ecosystem support.",
    overview:
      "Solana Hackathon brings builders together to ship consumer, DeFi, and infra projects on Solana with mentorship and prize pools.",
    ecosystemSlug: "solana",
    ecosystemSlugs: ["solana"],
    fundingRange: "$5K – $250K prizes",
    deadline: "Season 4 · Aug 2026",
    deadlineSortOrder: 202608,
    status: "upcoming",
    fundingType: "hackathon",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "student", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://solana.com/hackathon",
    websiteUrl: "https://solana.com/developers",
    addedAt: "2026-05-01",
    relatedApiSlugs: ["privy", "pyth"],
    relatedRecipeSlugs: ["solana-pay-store"],
  }),
  defineGrant({
    slug: "hyperliquid-builder-program",
    name: "Hyperliquid Builder Program",
    org: "Hyperliquid",
    description:
      "Grants for trading tools, bots and ecosystem apps on Hyperliquid.",
    overview:
      "The Hyperliquid Builder Program funds teams shipping trading frontends, analytics, and automation on Hyperliquid's perps infrastructure.",
    ecosystemSlug: "hyperliquid",
    ecosystemSlugs: ["hyperliquid"],
    fundingRange: "$10K – $100K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["solo-builder", "startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://hyperliquid.xyz",
    addedAt: "2026-01-20",
    relatedApiSlugs: ["hyperliquid", "pyth", "privy"],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "hyperliquid-copy-trading-bot"],
  }),
  defineGrant({
    slug: "arbitrum-grants",
    name: "Arbitrum Grants",
    org: "Arbitrum Foundation",
    description:
      "Funding for developers building on Arbitrum One and Orbit chains.",
    overview:
      "Arbitrum Grants fund dApps, tooling, and infrastructure that grow the Arbitrum ecosystem across L2 and Orbit deployments.",
    ecosystemSlug: "arbitrum",
    ecosystemSlugs: ["arbitrum"],
    fundingRange: "$10K – $250K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["startup", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://arbitrum.foundation",
    addedAt: "2026-01-10",
    relatedApiSlugs: ["alchemy", "the-graph", "walletconnect"],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "uniswap-pool-explorer"],
  }),
  defineGrant({
    slug: "optimism-retro-funding",
    name: "Optimism Retro Funding",
    org: "Optimism Collective",
    description:
      "Retroactive public goods funding for projects benefiting Optimism.",
    overview:
      "Retro Funding rewards teams that have already delivered measurable impact to the Optimism collective and Superchain ecosystem.",
    ecosystemSlug: "optimism",
    ecosystemSlugs: ["optimism"],
    fundingRange: "Variable",
    deadline: "Season 8 · Q3 2026",
    deadlineSortOrder: 202607,
    status: "upcoming",
    fundingType: "grant",
    fundingStages: ["mvp", "seed"],
    builderTypes: ["open-source", "startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://community.optimism.io",
    addedAt: "2025-11-01",
    importantDates: [
      { label: "Next funding season", value: "Season 8 · Q3 2026" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Grant" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "sui-builder-grants",
    name: "Sui Builder Grants",
    org: "Sui Foundation",
    description:
      "Funding for Move-based apps, tooling and developer education.",
    overview:
      "Sui Builder Grants support early-stage teams building DeFi, gaming, and infrastructure on the Sui network.",
    ecosystemSlug: "sui",
    ecosystemSlugs: ["sui"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["solo-builder", "startup", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://sui.io/developers",
    addedAt: "2026-01-05",
    relatedApiSlugs: ["pyth"],
    relatedRecipeSlugs: ["sui-kiosk-marketplace"],
  }),
  defineGrant({
    slug: "ethereum-esp",
    name: "Ethereum Foundation ESP",
    org: "Ethereum Foundation",
    description:
      "Grants for protocol research, core tooling and ecosystem growth.",
    overview:
      "The Ecosystem Support Program funds public goods, research, and developer tooling that strengthen Ethereum.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum"],
    fundingRange: "$10K – $500K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["open-source", "team", "startup"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://esp.ethereum.foundation",
    addedAt: "2025-12-01",
    relatedApiSlugs: ["alchemy", "the-graph", "dune"],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "ens-manager-app"],
  }),
  defineGrant({
    slug: "solana-foundation-grants",
    name: "Solana Foundation Grants",
    org: "Solana Foundation",
    description:
      "Support for open-source projects and ecosystem growth on Solana.",
    overview:
      "Solana Foundation Grants fund infrastructure, DeFi, and consumer apps that expand the Solana developer ecosystem.",
    ecosystemSlug: "solana",
    ecosystemSlugs: ["solana"],
    fundingRange: "$5K – $100K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://solana.org/grants",
    addedAt: "2026-01-12",
    relatedApiSlugs: ["privy", "pyth"],
    relatedRecipeSlugs: ["solana-pay-store"],
  }),
  defineGrant({
    slug: "polygon-community-grants",
    name: "Polygon Community Grants",
    org: "Polygon Labs",
    description:
      "Grants for apps and tooling on Polygon PoS and zkEVM.",
    overview:
      "Polygon Community Grants support teams building on Polygon's scaling stack with milestone-based funding.",
    ecosystemSlug: "polygon",
    ecosystemSlugs: ["polygon"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://polygon.technology",
    addedAt: "2026-01-08",
    relatedApiSlugs: ["alchemy", "the-graph", "dune"],
    relatedRecipeSlugs: ["quickswap-dex", "thirdweb-nft-marketplace"],
  }),
  defineGrant({
    slug: "avalanche-builder-rewards",
    name: "Avalanche Builder Rewards",
    org: "Ava Labs",
    description:
      "Incentives for dApps and infrastructure on Avalanche subnets.",
    overview:
      "Avalanche Builder Rewards fund teams launching on Avalanche C-Chain and custom subnets.",
    ecosystemSlug: "avalanche",
    ecosystemSlugs: ["avalanche"],
    fundingRange: "$5K – $75K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://build.avax.network",
    addedAt: "2026-01-18",
    relatedApiSlugs: ["alchemy", "dune"],
    relatedRecipeSlugs: ["pangolin-dex"],
  }),
  defineGrant({
    slug: "aptos-foundation-grants",
    name: "Aptos Foundation Grants",
    org: "Aptos Foundation",
    description:
      "Support for Move-based ecosystem projects on Aptos.",
    overview:
      "Aptos Foundation Grants fund DeFi, gaming, and developer tooling on the Aptos network.",
    ecosystemSlug: "aptos",
    ecosystemSlugs: ["aptos"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://aptosfoundation.org",
    addedAt: "2026-01-06",
    relatedApiSlugs: ["pyth"],
    relatedRecipeSlugs: ["thala-defi-app"],
  }),
  defineGrant({
    slug: "gitcoin-grants",
    name: "Gitcoin Grants",
    org: "Gitcoin",
    description:
      "Quadratic funding rounds for open-source public goods.",
    overview:
      "Gitcoin Grants run recurring quadratic funding rounds across multiple ecosystems for open-source builders.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "optimism", "polygon"],
    fundingRange: "Community-matched",
    deadline: "Round 22 · Jul 2026",
    deadlineSortOrder: 202607,
    status: "upcoming",
    fundingType: "grant",
    fundingStages: ["open-to-all"],
    builderTypes: ["open-source", "solo-builder", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://grants.gitcoin.co",
    addedAt: "2026-02-01",
    importantDates: [
      { label: "Next funding round", value: "Round 22 · Jul 2026" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Grant" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "pyth-grants",
    name: "Pyth Grants",
    org: "Pyth Network",
    description:
      "Funding for price feed integrations and data applications.",
    overview:
      "Pyth Grants support teams integrating or building on Pyth price feeds across supported chains.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "solana", "sui", "hyperliquid"],
    fundingRange: "$5K – $25K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://pyth.network",
    addedAt: "2026-01-14",
    relatedApiSlugs: ["pyth", "hyperliquid", "alchemy"],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "ai-trading-agent-demo"],
  }),
  defineGrant({
    slug: "immunefi-bug-bounties",
    name: "Immunefi Bug Bounties",
    org: "Immunefi",
    description:
      "Paid bounties for finding and reporting vulnerabilities in crypto protocols.",
    overview:
      "Immunefi connects security researchers with protocol teams offering bounties for critical smart contract and app vulnerabilities.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "arbitrum", "base"],
    fundingRange: "$1K – $10M",
    deadline: "Rolling",
    status: "active",
    fundingType: "bounty",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://immunefi.com/bug-bounty",
    websiteUrl: "https://immunefi.com",
    addedAt: "2026-02-20",
    relatedApiSlugs: ["immunefi", "alchemy"],
    relatedRecipeSlugs: ["web3-security-bounty-tracker"],
  }),
  defineGrant({
    slug: "berachain-ecosystem-fund",
    name: "Berachain Ecosystem Fund",
    org: "Berachain",
    description:
      "Early-stage funding for Berachain-native applications.",
    overview:
      "The Berachain Ecosystem Fund backs DeFi and gaming teams building on Berachain's proof-of-liquidity chain.",
    ecosystemSlug: "berachain",
    ecosystemSlugs: ["berachain"],
    fundingRange: "$10K – $50K",
    deadline: "Applications open",
    status: "upcoming",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "pre-seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://berachain.com",
    addedAt: "2026-03-10",
    importantDates: [
      { label: "Applications", value: "Open" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Ecosystem Fund" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "monad-ecosystem-grants",
    name: "Monad Ecosystem Grants",
    org: "Monad",
    description:
      "Builder grants for high-performance EVM apps on Monad.",
    overview:
      "Monad Ecosystem Grants fund early teams preparing for mainnet deployment on Monad's parallel EVM.",
    ecosystemSlug: "monad",
    ecosystemSlugs: ["monad"],
    fundingRange: "$5K – $50K",
    deadline: "Testnet phase",
    status: "upcoming",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "team", "solo-builder"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://monad.xyz",
    addedAt: "2026-03-05",
    importantDates: [
      { label: "Current phase", value: "Testnet" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Ecosystem Fund" },
      { label: "Location", value: "Global" },
    ],
  }),
];
