import { defineGrant } from "./grants-detail-defaults";

export const grantsDirectory = [
  defineGrant({
    slug: "base-builder-program",
    name: "Base Builder Program",
    org: "Coinbase",
    description:
      "Funding for apps, infra and developer tools shipping on Base.",
    overview:
      "Base Builder Program supports teams building consumer apps, DeFi, and infrastructure on Base with rolling applications and milestone-based payouts.",
    ecosystemSlug: "base",
    ecosystemSlugs: ["base"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["solo-builder", "startup", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://docs.base.org/get-started/get-funded",
    websiteUrl: "https://base.org/build",
    addedAt: "2026-02-15",
    relatedApiSlugs: ["privy", "alchemy", "dune"],
    relatedRecipeSlugs: ["onchain-commerce-shop", "base-social-mini-app"],
  }),
  defineGrant({
    slug: "alliance-accelerator",
    name: "Alliance Accelerator",
    org: "Alliance DAO",
    description:
      "Accelerator for crypto founders with mentorship, capital, and ecosystem intros.",
    overview:
      "Alliance Accelerator backs early crypto teams with capital, mentorship, and distribution support across DeFi, infra, and consumer apps.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base"],
    fundingRange: "$100K – $500K",
    deadline: "Cohort 12 · Sep 2026",
    deadlineSortOrder: 202609,
    status: "active",
    fundingType: "accelerator",
    fundingStages: ["pre-seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    websiteUrl: "https://alliance.xyz",
    addedAt: "2026-03-01",
    relatedApiSlugs: ["privy", "alchemy", "walletconnect"],
    relatedRecipeSlugs: ["defi-lending-app", "onchain-commerce-shop"],
  }),
  defineGrant({
    slug: "a16z-crypto-startup-school",
    name: "a16z Crypto Startup School",
    org: "a16z crypto",
    description:
      "Education and accelerator program for founders exploring crypto startup ideas.",
    overview:
      "a16z Crypto Startup School helps founders go from idea to fundable company with lectures, mentorship, and investor access.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "solana"],
    fundingRange: "Program access + network",
    deadline: "Class of 2026 · May 2026",
    deadlineSortOrder: 202605,
    status: "upcoming",
    fundingType: "accelerator",
    fundingTypeLabel: "Education + Accelerator",
    fundingStages: ["idea", "pre-seed"],
    builderTypes: ["solo-builder", "startup", "student"],
    location: "San Francisco + Remote",
    remoteFriendly: true,
    applyUrl: "https://a16zcrypto.com/accelerator",
    websiteUrl: "https://a16zcrypto.com",
    addedAt: "2026-04-01",
    relatedApiSlugs: ["privy", "alchemy"],
    relatedRecipeSlugs: ["onchain-agent-demo", "defi-lending-app"],
  }),
  defineGrant({
    slug: "solana-hackathon",
    name: "Solana Hackathon",
    org: "Solana Foundation",
    description:
      "Global hackathon for shipping Solana apps with prizes and ecosystem support.",
    overview:
      "Solana Hackathon brings builders together to ship consumer, DeFi, and infra projects on Solana with mentorship and prize pools.",
    ecosystemSlug: "solana",
    ecosystemSlugs: ["solana"],
    fundingRange: "$5K – $250K prizes",
    deadline: "Season 4 · Aug 2026",
    deadlineSortOrder: 202608,
    status: "upcoming",
    fundingType: "hackathon",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "student", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://solana.com/hackathon",
    websiteUrl: "https://solana.com/developers",
    addedAt: "2026-05-01",
    relatedApiSlugs: ["privy", "pyth"],
    relatedRecipeSlugs: ["solana-pay-store"],
  }),
  defineGrant({
    slug: "hyperliquid-builder-program",
    name: "Hyperliquid Builder Program",
    org: "Hyperliquid",
    description:
      "Grants for trading tools, bots and ecosystem apps on Hyperliquid.",
    overview:
      "The Hyperliquid Builder Program funds teams shipping trading frontends, analytics, and automation on Hyperliquid's perps infrastructure.",
    ecosystemSlug: "hyperliquid",
    ecosystemSlugs: ["hyperliquid"],
    fundingRange: "$10K – $100K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["solo-builder", "startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://hyperliquid.xyz/grant",
    addedAt: "2026-01-20",
    relatedApiSlugs: ["hyperliquid", "pyth", "privy"],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "hyperliquid-copy-trading-bot"],
  }),
  defineGrant({
    slug: "arbitrum-grants",
    name: "Arbitrum Grants",
    org: "Arbitrum Foundation",
    description:
      "Funding for developers building on Arbitrum One and Orbit chains.",
    overview:
      "Arbitrum Grants fund dApps, tooling, and infrastructure that grow the Arbitrum ecosystem across L2 and Orbit deployments.",
    ecosystemSlug: "arbitrum",
    ecosystemSlugs: ["arbitrum"],
    fundingRange: "$10K – $250K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["startup", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://arbitrum.foundation/grants",
    addedAt: "2026-01-10",
    relatedApiSlugs: ["alchemy", "the-graph", "walletconnect"],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "uniswap-pool-explorer"],
  }),
  defineGrant({
    slug: "optimism-retro-funding",
    name: "Optimism Retro Funding",
    org: "Optimism Collective",
    description:
      "Retroactive public goods funding for projects benefiting Optimism.",
    overview:
      "Retro Funding rewards teams that have already delivered measurable impact to the Optimism collective and Superchain ecosystem.",
    ecosystemSlug: "optimism",
    ecosystemSlugs: ["optimism"],
    fundingRange: "Variable",
    deadline: "Season 8 · Q3 2026",
    deadlineSortOrder: 202607,
    status: "upcoming",
    fundingType: "grant",
    fundingStages: ["mvp", "seed"],
    builderTypes: ["open-source", "startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://community.optimism.io/retropgf",
    addedAt: "2025-11-01",
    importantDates: [
      { label: "Next funding season", value: "Season 8 · Q3 2026" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Grant" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "sui-builder-grants",
    name: "Sui Builder Grants",
    org: "Sui Foundation",
    description:
      "Funding for Move-based apps, tooling and developer education.",
    overview:
      "Sui Builder Grants support early-stage teams building DeFi, gaming, and infrastructure on the Sui network.",
    ecosystemSlug: "sui",
    ecosystemSlugs: ["sui"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["solo-builder", "startup", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://suifoundation.org/grants",
    websiteUrl: "https://sui.io",
    addedAt: "2026-01-05",
    relatedApiSlugs: ["pyth"],
    relatedRecipeSlugs: ["sui-kiosk-marketplace"],
  }),
  defineGrant({
    slug: "ethereum-esp",
    name: "Ethereum Foundation ESP",
    org: "Ethereum Foundation",
    description:
      "Grants for protocol research, core tooling and ecosystem growth.",
    overview:
      "The Ecosystem Support Program funds public goods, research, and developer tooling that strengthen Ethereum.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum"],
    fundingRange: "$10K – $500K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "seed"],
    builderTypes: ["open-source", "team", "startup"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://esp.ethereum.foundation",
    addedAt: "2025-12-01",
    relatedApiSlugs: ["alchemy", "the-graph", "dune"],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "ens-manager-app"],
  }),
  defineGrant({
    slug: "solana-foundation-grants",
    name: "Solana Foundation Grants",
    org: "Solana Foundation",
    description:
      "Support for open-source projects and ecosystem growth on Solana.",
    overview:
      "Solana Foundation Grants fund infrastructure, DeFi, and consumer apps that expand the Solana developer ecosystem.",
    ecosystemSlug: "solana",
    ecosystemSlugs: ["solana"],
    fundingRange: "$5K – $100K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://solana.org/grants-funding",
    addedAt: "2026-01-12",
    relatedApiSlugs: ["privy", "pyth"],
    relatedRecipeSlugs: ["solana-pay-store"],
  }),
  defineGrant({
    slug: "polygon-community-grants",
    name: "Polygon Community Grants",
    org: "Polygon Labs",
    description:
      "Grants for apps and tooling on Polygon PoS and zkEVM.",
    overview:
      "Polygon Community Grants support teams building on Polygon's scaling stack with milestone-based funding.",
    ecosystemSlug: "polygon",
    ecosystemSlugs: ["polygon"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://polygon.technology/grow",
    addedAt: "2026-01-08",
    relatedApiSlugs: ["alchemy", "the-graph", "dune"],
    relatedRecipeSlugs: ["quickswap-dex", "thirdweb-nft-marketplace"],
  }),
  defineGrant({
    slug: "avalanche-builder-rewards",
    name: "Avalanche Builder Rewards",
    org: "Ava Labs",
    description:
      "Incentives for dApps and infrastructure on Avalanche subnets.",
    overview:
      "Avalanche Builder Rewards fund teams launching on Avalanche C-Chain and custom subnets.",
    ecosystemSlug: "avalanche",
    ecosystemSlugs: ["avalanche"],
    fundingRange: "$5K – $75K",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://build.avax.network/grants",
    addedAt: "2026-01-18",
    relatedApiSlugs: ["alchemy", "dune"],
    relatedRecipeSlugs: ["pangolin-dex"],
  }),
  defineGrant({
    slug: "aptos-foundation-grants",
    name: "Aptos Foundation Grants",
    org: "Aptos Foundation",
    description:
      "Support for Move-based ecosystem projects on Aptos.",
    overview:
      "Aptos Foundation Grants fund DeFi, gaming, and developer tooling on the Aptos network.",
    ecosystemSlug: "aptos",
    ecosystemSlugs: ["aptos"],
    fundingRange: "$5K – $50K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://aptosfoundation.org/grants",
    websiteUrl: "https://aptosfoundation.org",
    addedAt: "2026-01-06",
    relatedApiSlugs: ["pyth"],
    relatedRecipeSlugs: ["thala-defi-app"],
  }),
  defineGrant({
    slug: "gitcoin-grants",
    name: "Gitcoin Grants",
    org: "Gitcoin",
    description:
      "Quadratic funding rounds for open-source public goods.",
    overview:
      "Gitcoin Grants run recurring quadratic funding rounds across multiple ecosystems for open-source builders.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "optimism", "polygon"],
    fundingRange: "Community-matched",
    deadline: "Round 22 · Jul 2026",
    deadlineSortOrder: 202607,
    status: "upcoming",
    fundingType: "grant",
    fundingStages: ["open-to-all"],
    builderTypes: ["open-source", "solo-builder", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://grants.gitcoin.co",
    addedAt: "2026-02-01",
    importantDates: [
      { label: "Next funding round", value: "Round 22 · Jul 2026" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Grant" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "pyth-grants",
    name: "Pyth Grants",
    org: "Pyth Network",
    description:
      "Funding for price feed integrations and data applications.",
    overview:
      "Pyth Grants support teams integrating or building on Pyth price feeds across supported chains.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "solana", "sui", "hyperliquid"],
    fundingRange: "$5K – $25K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://legacy.pyth.network/grants",
    websiteUrl: "https://www.pyth.network/",
    addedAt: "2026-01-14",
    relatedApiSlugs: ["pyth", "hyperliquid", "alchemy"],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "ai-trading-agent-demo"],
  }),
  defineGrant({
    slug: "immunefi-bug-bounties",
    name: "Immunefi Bug Bounties",
    org: "Immunefi",
    description:
      "Paid bounties for finding and reporting vulnerabilities in crypto protocols.",
    overview:
      "Immunefi connects security researchers with protocol teams offering bounties for critical smart contract and app vulnerabilities.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "arbitrum", "base"],
    fundingRange: "$1K – $10M",
    deadline: "Rolling",
    status: "active",
    fundingType: "bounty",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "open-source", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://immunefi.com",
    websiteUrl: "https://immunefi.com",
    addedAt: "2026-02-20",
    relatedApiSlugs: ["immunefi", "alchemy"],
    relatedRecipeSlugs: ["web3-security-bounty-tracker"],
  }),
  defineGrant({
    slug: "berachain-ecosystem-fund",
    name: "Berachain Ecosystem Fund",
    org: "Berachain",
    description:
      "Early-stage funding for Berachain-native applications.",
    overview:
      "The Berachain Ecosystem Fund backs DeFi and gaming teams building on Berachain's proof-of-liquidity chain.",
    ecosystemSlug: "berachain",
    ecosystemSlugs: ["berachain"],
    fundingRange: "$10K – $50K",
    deadline: "Applications open",
    status: "upcoming",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "pre-seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    websiteUrl: "https://www.berachain.com",
    addedAt: "2026-03-10",
    importantDates: [
      { label: "Applications", value: "Open" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Ecosystem Fund" },
      { label: "Location", value: "Global" },
    ],
  }),
  defineGrant({
    slug: "monad-ecosystem-grants",
    name: "Monad Ecosystem Grants",
    org: "Monad",
    description:
      "Builder grants for high-performance EVM apps on Monad.",
    overview:
      "Monad Ecosystem Grants fund early teams preparing for mainnet deployment on Monad's parallel EVM.",
    ecosystemSlug: "monad",
    ecosystemSlugs: ["monad"],
    fundingRange: "$5K – $50K",
    deadline: "Testnet phase",
    status: "upcoming",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["startup", "team", "solo-builder"],
    location: "Global",
    remoteFriendly: true,
    websiteUrl: "https://www.monad.xyz",
    addedAt: "2026-03-05",
    importantDates: [
      { label: "Current phase", value: "Testnet" },
      { label: "Program status", value: "Upcoming" },
      { label: "Funding type", value: "Ecosystem Fund" },
      { label: "Location", value: "Global" },
    ],
  }),

  // Hackathons
  defineGrant({
    slug: "ethglobal",
    name: "ETHGlobal",
    org: "ETHGlobal",
    description:
      "Global Ethereum hackathon series with multiple in-person and online events each year.",
    overview:
      "ETHGlobal runs flagship hackathons worldwide where teams ship Ethereum apps in days with mentorship, prizes, and sponsor bounties.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "arbitrum", "optimism"],
    fundingRange: "Prizes vary by event",
    deadline: "Multiple events per year",
    status: "active",
    fundingType: "hackathon",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "student", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://ethglobal.com",
    websiteUrl: "https://ethglobal.com",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["alchemy", "privy", "walletconnect"],
    relatedRecipeSlugs: ["scaffold-eth-2", "farcaster-mini-app-full-demo"],
  }),
  defineGrant({
    slug: "ethglobal-new-york-2026",
    name: "ETHGlobal New York 2026",
    org: "ETHGlobal",
    description:
      "In-person Ethereum hackathon in New York, June 12–14, 2026.",
    overview:
      "Three-day ETHGlobal hackathon in NYC to build and demo Ethereum projects with on-site mentors and sponsor prizes.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base"],
    fundingRange: "Event prizes + sponsor bounties",
    deadline: "Jun 12–14, 2026 · New York",
    deadlineSortOrder: 202606,
    status: "upcoming",
    fundingType: "hackathon",
    fundingStages: ["open-to-all"],
    builderTypes: ["solo-builder", "student", "team"],
    location: "New York, USA",
    remoteFriendly: false,
    applyUrl: "https://ethglobal.com/events/newyork2026",
    websiteUrl: "https://ethglobal.com/events/newyork2026",
    addedAt: "2026-06-02",
    importantDates: [
      { label: "Event dates", value: "Jun 12–14, 2026" },
      { label: "Location", value: "New York" },
      { label: "Format", value: "In-person hackathon" },
    ],
    relatedApiSlugs: ["alchemy", "privy"],
    relatedRecipeSlugs: ["scaffold-eth-2", "developer-dao-web3-starter-kits"],
  }),

  // Ecosystem grants
  defineGrant({
    slug: "starknet-seed-grants",
    name: "Starknet Seed Grants",
    org: "Starknet Foundation",
    description:
      "Up to $25K non-dilutive funding for MVP and proof-of-concept builds on Starknet.",
    overview:
      "Seed Grants support early teams validating product ideas on Starknet with milestone-based non-dilutive capital.",
    ecosystemSlug: "starknet",
    ecosystemSlugs: ["starknet", "ethereum"],
    fundingRange: "Up to $25K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["solo-builder", "startup", "team", "open-source"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://www.starknet.io/grants",
    websiteUrl: "https://www.starknet.io",
    addedAt: "2026-06-02",
    relatedRecipeSlugs: ["jediswap-dex"],
  }),
  defineGrant({
    slug: "starknet-growth-grants",
    name: "Starknet Growth Grants",
    org: "Starknet Foundation",
    description:
      "Up to $1M for later-stage projects with live traction on Starknet.",
    overview:
      "Growth Grants back teams with measurable usage and revenue preparing to scale on Starknet mainnet.",
    ecosystemSlug: "starknet",
    ecosystemSlugs: ["starknet"],
    fundingRange: "Up to $1M",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["seed", "series-a-plus"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://www.starknet.io/grants",
    websiteUrl: "https://www.starknet.io",
    addedAt: "2026-06-02",
    relatedRecipeSlugs: ["jediswap-dex"],
  }),
  defineGrant({
    slug: "web3-foundation-grants",
    name: "Web3 Foundation Grants",
    org: "Web3 Foundation",
    description:
      "Funding for open-source software and research on Polkadot and Substrate.",
    overview:
      "Web3 Foundation Grants fund teams building core infrastructure, tooling, and research for the Polkadot ecosystem.",
    ecosystemSlug: "polkadot",
    ecosystemSlugs: ["polkadot"],
    fundingRange: "Varies by milestone",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp", "seed"],
    builderTypes: ["open-source", "team", "startup"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://grants.web3.foundation",
    websiteUrl: "https://web3.foundation",
    addedAt: "2026-06-02",
    relatedRecipeSlugs: [],
  }),
  defineGrant({
    slug: "scroll-community-grants",
    name: "Scroll Community Grants",
    org: "Scroll",
    description:
      "Grants for communities and developers building on Scroll.",
    overview:
      "Scroll Community Grants support developer communities, tooling, and apps growing the Scroll zkEVM ecosystem.",
    ecosystemSlug: "scroll",
    ecosystemSlugs: ["scroll", "ethereum"],
    fundingRange: "Varies",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingStages: ["prototype", "mvp"],
    builderTypes: ["open-source", "team", "startup", "solo-builder"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://grants.scroll.io/programs/community-grants/",
    websiteUrl: "https://grants.scroll.io",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["alchemy"],
    relatedRecipeSlugs: ["scaffold-eth-2"],
  }),
  defineGrant({
    slug: "celo-camp",
    name: "Celo Camp",
    org: "Celo",
    description:
      "Flagship accelerator for projects building on Celo with no equity taken.",
    overview:
      "Celo Camp helps early teams refine product, distribution, and go-to-market for real-world payment and mobile-first apps on Celo.",
    ecosystemSlug: "celo",
    ecosystemSlugs: ["celo"],
    fundingRange: "Program benefits + network",
    deadline: "Cohort applications · Rolling",
    status: "active",
    fundingType: "accelerator",
    fundingTypeLabel: "No-equity Accelerator",
    fundingStages: ["pre-seed", "mvp"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://www.celocamp.com/",
    websiteUrl: "https://celo.org",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["circle", "privy"],
    relatedRecipeSlugs: ["onramp-demo-app"],
  }),

  // Microgrants
  defineGrant({
    slug: "superteam-earn",
    name: "Superteam Earn",
    org: "Superteam",
    description:
      "Up to $10K microgrants for Solana builders in emerging markets.",
    overview:
      "Superteam Earn funds small, fast grants for Solana projects across emerging-market Superteam chapters.",
    ecosystemSlug: "solana",
    ecosystemSlugs: ["solana"],
    fundingRange: "Up to $10K",
    deadline: "Rolling",
    status: "active",
    fundingType: "grant",
    fundingTypeLabel: "Microgrant",
    fundingStages: ["idea", "prototype", "mvp"],
    builderTypes: ["solo-builder", "student", "team", "open-source"],
    location: "Emerging markets",
    remoteFriendly: true,
    applyUrl: "https://earn.superteam.fun/",
    websiteUrl: "https://superteam.fun",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["helius", "jupiter-sdk"],
    relatedRecipeSlugs: ["solana-dapp-scaffold", "solanahub-freelance-marketplace"],
  }),
  defineGrant({
    slug: "dydx-ecosystem-grants",
    name: "dYdX Ecosystem Grants",
    org: "dYdX Foundation",
    description:
      "Funding for tools and integrations on dYdX Chain — $14M+ awarded to date.",
    overview:
      "dYdX Ecosystem Grants back developers building trading tools, analytics, and integrations for the dYdX Chain Cosmos app.",
    ecosystemSlug: "cosmos",
    ecosystemSlugs: ["cosmos"],
    fundingRange: "$14M+ program total",
    deadline: "Rolling",
    status: "active",
    fundingType: "ecosystem-fund",
    fundingStages: ["prototype", "mvp", "seed"],
    builderTypes: ["startup", "team", "open-source", "solo-builder"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://www.dydxgrants.com/",
    websiteUrl: "https://dydx.exchange",
    addedAt: "2026-06-02",
    relatedRecipeSlugs: ["cosmjs", "skip-protocol"],
  }),

  // Accelerators
  defineGrant({
    slug: "techstars-web3",
    name: "Techstars Web3",
    org: "Techstars",
    description:
      "$120K for 6% equity — 13-week intensive accelerator, 2026 applications open.",
    overview:
      "Techstars Web3 is a global accelerator pairing early Web3 startups with mentors, investors, and a structured 13-week program.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "base", "solana", "multi-chain"],
    fundingRange: "$120K for 6% equity",
    deadline: "2026 applications open",
    deadlineSortOrder: 202612,
    status: "active",
    fundingType: "accelerator",
    fundingStages: ["pre-seed", "seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    applyUrl: "https://www.techstars.com/accelerators",
    websiteUrl: "https://www.techstars.com",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["privy", "alchemy"],
    relatedRecipeSlugs: ["onchain-agent-demo"],
  }),
  defineGrant({
    slug: "yzi-labs",
    name: "YZi Labs",
    org: "YZi Labs",
    description:
      "Early-stage Web3 startup funding and global exposure (formerly Binance Labs).",
    overview:
      "YZi Labs invests in early Web3 founders with capital, exchange ecosystem access, and strategic distribution support.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "solana", "multi-chain"],
    fundingRange: "Seed-stage investment",
    deadline: "Rolling",
    status: "active",
    fundingType: "venture-program",
    fundingStages: ["pre-seed", "seed"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    websiteUrl: "https://www.yzilabs.com/",
    addedAt: "2026-06-02",
  }),
  defineGrant({
    slug: "coinlist-seed",
    name: "CoinList Seed",
    org: "CoinList",
    description:
      "Growth program for teams approaching a token launch.",
    overview:
      "CoinList Seed helps projects prepare for compliant token launches with distribution, community, and go-to-market support.",
    ecosystemSlug: "ethereum",
    ecosystemSlugs: ["ethereum", "solana", "multi-chain"],
    fundingRange: "Program + launch support",
    deadline: "Rolling",
    status: "active",
    fundingType: "startup-program",
    fundingStages: ["seed", "series-a-plus"],
    builderTypes: ["startup", "team"],
    location: "Global",
    remoteFriendly: true,
    websiteUrl: "https://blog.coinlist.co/",
    addedAt: "2026-06-02",
    relatedApiSlugs: ["circle", "privy"],
  }),
];
