import type { RecipeEntry } from "./recipe-directory-types";
import { recipeCatalogAdditionInputs } from "./recipe-directory-additions";

type RecipeInput = Omit<RecipeEntry, "links" | "gettingStartedLinks" | "relatedRecipeSlugs" | "techStack" | "screenshots"> & {
  techStack?: string[];
  screenshots?: string[];
  links?: RecipeEntry["links"];
  gettingStartedLinks?: RecipeEntry["gettingStartedLinks"];
  relatedRecipeSlugs?: string[];
};

function defineRecipe(input: RecipeInput): RecipeEntry {
  return {
    techStack: input.techStack ?? [],
    screenshots: input.screenshots ?? [],
    links: input.links ?? [],
    gettingStartedLinks: input.gettingStartedLinks ?? [],
    relatedRecipeSlugs: input.relatedRecipeSlugs ?? [],
    ...input,
  };
}

export const recipeDirectory: RecipeEntry[] = [
  defineRecipe({
    slug: "agentkit",
    name: "AgentKit",
    description:
      "Build AI agents that can own wallets, send transactions and interact with blockchain networks.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["ai", "wallets", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Coinbase",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: [
      "AgentKit",
      "TypeScript",
      "CDP SDK",
      "Wallet Automation",
      "Onchain Actions",
    ],
    logoSlug: "coinbase",
    githubUrl: "https://github.com/coinbase/agentkit",
    docsUrl: "https://docs.cdp.coinbase.com/agent-kit/welcome",
    sourceUrl: "https://docs.cdp.coinbase.com/agent-kit/welcome",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/coinbase/agentkit" },
      {
        label: "Documentation",
        url: "https://docs.cdp.coinbase.com/agent-kit/welcome",
      },
    ],
    gettingStartedLinks: [
      {
        label: "AgentKit Welcome",
        url: "https://docs.cdp.coinbase.com/agent-kit/welcome",
      },
      {
        label: "Example Agents",
        url: "https://github.com/coinbase/agentkit/tree/main/typescript/examples",
      },
    ],
    relatedRecipeSlugs: [
      "onchain-agent-demo",
      "onchain-commerce-shop",
    ],
  }),
  defineRecipe({
    slug: "onchain-agent-demo",
    name: "Onchain Agent Demo",
    description:
      "A Next.js application showing how to build an AI agent capable of performing onchain operations.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["ai", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Coinbase",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["Next.js", "AgentKit", "GPT", "Wallet Actions"],
    logoSlug: "coinbase",
    githubUrl: "https://github.com/coinbase/onchain-agent-demo",
    sourceUrl: "https://github.com/coinbase/onchain-agent-demo",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/coinbase/onchain-agent-demo",
      },
    ],
    gettingStartedLinks: [
      {
        label: "Repository README",
        url: "https://github.com/coinbase/onchain-agent-demo#readme",
      },
    ],
    relatedRecipeSlugs: ["agentkit", "xmtp-messaging-agent", "fluora-agentkit-example"],
  }),
  defineRecipe({
    slug: "onramp-demo-app",
    name: "Onramp Demo App",
    description:
      "Demo app for funding crypto wallets with fiat via Coinbase Onramp and embedded wallets.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["payments", "wallets"],
    sourceType: "template",
    sourceLabel: "Coinbase CDP",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: [
      "Coinbase Onramp",
      "Embedded Wallets",
      "Smart Accounts",
      "Mobile",
    ],
    logoSlug: "coinbase",
    docsUrl:
      "https://docs.cdp.coinbase.com/get-started/demo-apps/starter/onramp-demo-app",
    sourceUrl:
      "https://docs.cdp.coinbase.com/get-started/demo-apps/starter/onramp-demo-app",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "Documentation",
        url: "https://docs.cdp.coinbase.com/get-started/demo-apps/starter/onramp-demo-app",
      },
    ],
    gettingStartedLinks: [
      {
        label: "Onramp Demo Guide",
        url: "https://docs.cdp.coinbase.com/get-started/demo-apps/starter/onramp-demo-app",
      },
    ],
    relatedRecipeSlugs: ["onchain-commerce-shop", "onramp-demo-app", "automated-mass-payouts"],
  }),
  defineRecipe({
    slug: "automated-mass-payouts",
    name: "Automated Mass Payouts",
    description:
      "Example application for automating payroll, rewards and bulk crypto transfers.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["payments", "cards"],
    sourceType: "demo-app",
    sourceLabel: "Coinbase CDP",
    ecosystems: ["Base", "Ethereum"],
    apis: [
      { slug: "circle", name: "Circle" },
      { slug: "rain", name: "Rain" },
    ],
    techStack: ["CDP SDK", "USDC", "Batch Transfers", "Treasury", "Payroll"],
    logoSlug: "coinbase",
    docsUrl: "https://docs.cdp.coinbase.com/get-started/demo-apps/",
    sourceUrl: "https://docs.cdp.coinbase.com/get-started/demo-apps/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "CDP Demo Apps",
        url: "https://docs.cdp.coinbase.com/get-started/demo-apps/",
      },
      { label: "CDP Docs", url: "https://docs.cdp.coinbase.com/" },
    ],
    gettingStartedLinks: [
      {
        label: "Demo Apps Collection",
        url: "https://docs.cdp.coinbase.com/get-started/demo-apps/",
      },
    ],
    relatedRecipeSlugs: ["payroll-dashboard", "onramp-demo-app", "onchain-commerce-shop"],
  }),
  defineRecipe({
    slug: "xmtp-messaging-agent",
    name: "XMTP Messaging Agent",
    description:
      "Conversational crypto agent that sends payments and trade alerts over XMTP chat.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["ai", "infrastructure"],
    sourceType: "github",
    sourceLabel: "XMTP",
    ecosystems: ["Ethereum", "Base"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: ["XMTP", "TypeScript", "Messaging Agents", "AI Agents"],
    logoSlug: "xmtp",
    githubUrl: "https://github.com/xmtplabs/xmtp-agent-examples",
    sourceUrl: "https://github.com/xmtplabs/xmtp-agent-examples",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/xmtplabs/xmtp-agent-examples",
      },
    ],
    gettingStartedLinks: [
      {
        label: "Examples README",
        url: "https://github.com/xmtplabs/xmtp-agent-examples/blob/main/README.md",
      },
    ],
    relatedRecipeSlugs: ["agentkit", "onchain-agent-demo", "hey-social-app"],
  }),
  defineRecipe({
    slug: "fluora-agentkit-example",
    name: "Fluora AgentKit Example",
    description:
      "Example AI agent combining AgentKit with blockchain interactions for real-world crypto operations.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["ai", "wallets"],
    sourceType: "github",
    sourceLabel: "Community",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["AgentKit", "TypeScript", "Wallet Management", "AI Agents"],
    logoSlug: "coinbase",
    githubUrl: "https://github.com/fluora-ai/agentkit-fluora-example",
    sourceUrl: "https://github.com/fluora-ai/agentkit-fluora-example",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/fluora-ai/agentkit-fluora-example",
      },
    ],
    gettingStartedLinks: [
      {
        label: "Repository README",
        url: "https://github.com/fluora-ai/agentkit-fluora-example#readme",
      },
    ],
    relatedRecipeSlugs: ["onchain-agent-demo", "agentkit", "xmtp-messaging-agent"],
  }),
  defineRecipe({
    slug: "onchain-commerce-shop",
    name: "Onchain Commerce Shop",
    description:
      "Commerce starter application for selling products onchain with wallet checkout and USDC payments.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["payments", "wallets"],
    sourceType: "template",
    sourceLabel: "Coinbase CDP",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["Next.js", "OnchainKit", "USDC", "Tailwind CSS"],
    logoSlug: "coinbase",
    githubUrl: "https://github.com/coinbase/onchain-commerce-template",
    docsUrl: "https://docs.cdp.coinbase.com/",
    sourceUrl: "https://github.com/coinbase/onchain-commerce-template",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/coinbase/onchain-commerce-template" },
      { label: "CDP Docs", url: "https://docs.cdp.coinbase.com/" },
    ],
    gettingStartedLinks: [
      { label: "Deploy Template", url: "https://github.com/coinbase/onchain-commerce-template#readme" },
    ],
    relatedRecipeSlugs: ["agentkit", "onramp-demo-app", "thirdweb-nft-marketplace"],
  }),
  defineRecipe({
    slug: "defi-lending-app",
    name: "DeFi Lending App",
    description:
      "Full lending interface for supplying assets, borrowing, and monitoring health factors on Aave markets.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Aave",
    ecosystems: ["Ethereum", "Arbitrum", "Base"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Viem", "Aave SDK", "TypeScript"],
    logoSlug: "aave",
    githubUrl: "https://github.com/aave/interface",
    docsUrl: "https://docs.aave.com/developers/",
    sourceUrl: "https://github.com/aave/interface",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/aave/interface" },
      { label: "Developer Docs", url: "https://docs.aave.com/developers/" },
    ],
    gettingStartedLinks: [
      { label: "Integrating Aave", url: "https://docs.aave.com/developers/getting-started/readme" },
    ],
    relatedRecipeSlugs: ["portfolio-tracker", "defi-analytics-dashboard", "uniswap-pool-explorer"],
  }),
  defineRecipe({
    slug: "hyperliquid-trading-bot",
    name: "Hyperliquid Trading Bot",
    description:
      "Automated bot for placing orders, streaming market data, and firing alerts on Hyperliquid perps.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "github",
    sourceLabel: "Open Source GitHub Projects",
    ecosystems: ["Hyperliquid"],
    apis: [
      { slug: "hyperliquid", name: "Hyperliquid" },
      { slug: "pyth", name: "Pyth" },
      { slug: "telegram", name: "Telegram" },
    ],
    techStack: ["Python", "WebSocket", "Hyperliquid API"],
    logoSlug: "hyperliquid",
    githubUrl: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk",
    docsUrl: "https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api",
    sourceUrl: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk" },
      { label: "API Docs", url: "https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api" },
    ],
    gettingStartedLinks: [
      { label: "Python SDK", url: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk#usage" },
    ],
    relatedRecipeSlugs: ["hyperliquid-copy-trading-bot", "portfolio-tracker"],
  }),
  defineRecipe({
    slug: "thirdweb-nft-marketplace",
    name: "NFT Marketplace",
    description:
      "Deployable NFT marketplace for minting, listing, and trading collections with wallet checkout.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["wallets", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "thirdweb",
    ecosystems: ["Ethereum", "Polygon", "Base", "Arbitrum"],
    apis: [
      { slug: "alchemy", name: "Alchemy" },
      { slug: "privy", name: "Privy" },
    ],
    techStack: ["thirdweb SDK", "Next.js", "Solidity", "TypeScript"],
    logoSlug: "thirdweb",
    githubUrl: "https://github.com/thirdweb-dev/nft-marketplace-v3",
    docsUrl: "https://portal.thirdweb.com/templates/nft-marketplace",
    sourceUrl: "https://github.com/thirdweb-dev/nft-marketplace-v3",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/thirdweb-dev/nft-marketplace-v3" },
      { label: "Marketplace Template", url: "https://portal.thirdweb.com/templates/nft-marketplace" },
    ],
    gettingStartedLinks: [
      { label: "Deploy Marketplace", url: "https://github.com/thirdweb-dev/nft-marketplace-v3#readme" },
    ],
    relatedRecipeSlugs: ["onchain-commerce-shop", "alchemy-nft-gallery"],
  }),
  defineRecipe({
    slug: "alchemy-nft-gallery",
    name: "NFT Gallery App",
    description:
      "Browse wallet NFT collections, view metadata, and build gallery experiences with indexed on-chain data.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["wallets", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Alchemy",
    ecosystems: ["Ethereum", "Base"],
    apis: [
      { slug: "alchemy", name: "Alchemy" },
      { slug: "the-graph", name: "The Graph" },
    ],
    techStack: ["Next.js", "Alchemy NFT API", "IPFS", "Tailwind CSS"],
    logoSlug: "alchemy",
    githubUrl: "https://github.com/alchemyplatform/nft-demo-app",
    docsUrl: "https://docs.alchemy.com/docs/nft-api",
    sourceUrl: "https://github.com/alchemyplatform/nft-demo-app",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/alchemyplatform/nft-demo-app" },
      { label: "NFT API Docs", url: "https://docs.alchemy.com/docs/nft-api" },
    ],
    gettingStartedLinks: [
      { label: "NFT API Guide", url: "https://docs.alchemy.com/docs/nft-api-quickstart" },
    ],
    relatedRecipeSlugs: ["thirdweb-nft-marketplace", "onchain-commerce-shop"],
  }),
  defineRecipe({
    slug: "payroll-dashboard",
    name: "Payroll Dashboard",
    description:
      "Contractor payout dashboard with bank linking, batch transfers, and audit-friendly records.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["payments", "cards"],
    sourceType: "demo-app",
    sourceLabel: "Official SDK Examples",
    ecosystems: ["Ethereum", "Base"],
    apis: [
      { slug: "stripe", name: "Stripe" },
      { slug: "plaid", name: "Plaid" },
      { slug: "rain", name: "Rain" },
    ],
    techStack: ["Next.js", "Stripe Connect", "Plaid", "PostgreSQL"],
    logoSlug: "stripe",
    githubUrl: "https://github.com/stripe-samples/connect-onboarding-for-standard",
    docsUrl: "https://docs.stripe.com/connect",
    sourceUrl: "https://github.com/stripe-samples/connect-onboarding-for-standard",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/stripe-samples/connect-onboarding-for-standard" },
      { label: "Stripe Connect", url: "https://docs.stripe.com/connect" },
    ],
    gettingStartedLinks: [
      { label: "Connect Onboarding", url: "https://docs.stripe.com/connect/onboarding" },
    ],
    relatedRecipeSlugs: ["onchain-commerce-shop", "portfolio-tracker"],
  }),
  defineRecipe({
    slug: "portfolio-tracker",
    name: "Portfolio Tracker",
    description:
      "Track wallet positions, protocol exposure, and PnL across chains with live on-chain data.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["analytics", "trading"],
    sourceType: "github",
    sourceLabel: "Open Source GitHub Projects",
    ecosystems: ["Ethereum", "Arbitrum", "Base"],
    apis: [
      { slug: "the-graph", name: "The Graph" },
      { slug: "dune", name: "Dune" },
      { slug: "alchemy", name: "Alchemy" },
    ],
    techStack: ["React", "GraphQL", "Viem", "Recharts"],
    logoSlug: "dune",
    githubUrl: "https://github.com/wagmi-dev/wagmi/tree/main/examples",
    docsUrl: "https://docs.dune.com/",
    sourceUrl: "https://github.com/wagmi-dev/wagmi/tree/main/examples",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/wagmi-dev/wagmi/tree/main/examples" },
      { label: "Dune Docs", url: "https://docs.dune.com/" },
    ],
    gettingStartedLinks: [
      { label: "Subgraph Queries", url: "https://thegraph.com/docs/en/subgraphs/quick-start/" },
    ],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "defi-lending-app"],
  }),
  defineRecipe({
    slug: "defi-analytics-dashboard",
    name: "DeFi Analytics Dashboard",
    description:
      "Protocol metrics dashboard with SQL queries, wallet cohorts, and on-chain KPI panels.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["analytics", "infrastructure"],
    sourceType: "tutorial",
    sourceLabel: "Ecosystem Examples",
    ecosystems: ["Ethereum", "Base", "Arbitrum"],
    apis: [
      { slug: "dune", name: "Dune" },
      { slug: "the-graph", name: "The Graph" },
    ],
    techStack: ["Dune SQL", "React", "The Graph", "TypeScript"],
    logoSlug: "dune",
    docsUrl: "https://docs.dune.com/",
    sourceUrl: "https://dune.com/browse/dashboards",
    videoUrl: "https://www.youtube.com/embed/sOcaowLrXCM",
    isOpenSource: false,
    isFree: true,
    links: [
      { label: "Dune Docs", url: "https://docs.dune.com/" },
      { label: "Dashboard Gallery", url: "https://dune.com/browse/dashboards" },
    ],
    gettingStartedLinks: [
      { label: "Query Quickstart", url: "https://docs.dune.com/query-engine/quickstart" },
    ],
    relatedRecipeSlugs: ["portfolio-tracker", "defi-lending-app"],
  }),
  defineRecipe({
    slug: "hyperliquid-copy-trading-bot",
    name: "Copy Trading Bot",
    description:
      "Mirror top trader fills on Hyperliquid and push signals to Telegram subscribers.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "github",
    sourceLabel: "Community Showcases",
    ecosystems: ["Hyperliquid"],
    apis: [
      { slug: "hyperliquid", name: "Hyperliquid" },
      { slug: "telegram", name: "Telegram" },
      { slug: "privy", name: "Privy" },
    ],
    techStack: ["Python", "Hyperliquid API", "Telegram Bot API"],
    logoSlug: "hyperliquid",
    githubUrl: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk",
    sourceUrl: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk" },
    ],
    gettingStartedLinks: [
      { label: "Bot API", url: "https://core.telegram.org/bots/api" },
    ],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "tribe-mini-app", "portfolio-tracker"],
  }),
  defineRecipe({
    slug: "ai-trading-agent-demo",
    name: "AI Trading Agent Demo",
    description:
      "LLM agent that reads market data, proposes trades, and sends alerts — forkable hackathon demo.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["ai", "trading"],
    sourceType: "demo-app",
    sourceLabel: "Hackathon Projects",
    ecosystems: ["Hyperliquid", "Base"],
    apis: [
      { slug: "ollama", name: "Ollama" },
      { slug: "hyperliquid", name: "Hyperliquid" },
      { slug: "pyth", name: "Pyth" },
    ],
    techStack: ["Python", "Ollama", "LangChain", "Hyperliquid API"],
    logoSlug: "ollama",
    githubUrl: "https://github.com/ollama/ollama",
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    sourceUrl: "https://github.com/ollama/ollama",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/ollama/ollama" },
      { label: "API Docs", url: "https://github.com/ollama/ollama/blob/main/docs/api.md" },
    ],
    gettingStartedLinks: [
      { label: "Run Ollama Locally", url: "https://github.com/ollama/ollama#quickstart" },
    ],
    relatedRecipeSlugs: ["agentkit", "hyperliquid-trading-bot"],
  }),
  defineRecipe({
    slug: "solana-pay-store",
    name: "Solana Pay Store",
    description:
      "Crypto checkout store accepting SOL and USDC payments via Solana Pay QR codes and wallet transfers.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["payments", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Solana",
    ecosystems: ["Solana"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: ["React", "Solana Pay", "Solana Web3.js", "TypeScript"],
    logoSlug: "solana",
    githubUrl: "https://github.com/solana-developers/solana-payments-app-demo",
    docsUrl: "https://docs.solanapay.com/",
    sourceUrl: "https://github.com/solana-developers/solana-payments-app-demo",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/solana-developers/solana-payments-app-demo" },
      { label: "Solana Pay Docs", url: "https://docs.solanapay.com/" },
    ],
    gettingStartedLinks: [
      { label: "Payments Demo", url: "https://github.com/solana-developers/solana-payments-app-demo#readme" },
    ],
    relatedRecipeSlugs: ["onchain-commerce-shop", "thirdweb-nft-marketplace"],
  }),
  defineRecipe({
    slug: "base-social-mini-app",
    name: "Base Social Mini App",
    description:
      "Farcaster mini app on Base with wallet context, onchain actions, and in-feed commerce flows.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: ["Next.js", "OnchainKit", "Farcaster Mini Apps", "Base"],
    logoSlug: "base",
    githubUrl: "https://github.com/coinbase/build-onbase-apps",
    docsUrl: "https://docs.base.org/mini-apps",
    sourceUrl: "https://github.com/coinbase/build-onbase-apps",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/coinbase/build-onbase-apps" },
      { label: "Mini Apps Docs", url: "https://docs.base.org/mini-apps" },
    ],
    gettingStartedLinks: [
      { label: "Build on Base", url: "https://github.com/coinbase/build-onbase-apps#readme" },
    ],
    relatedRecipeSlugs: ["onchain-commerce-shop", "farcaster-mint-frame", "tribe-mini-app"],
  }),
  defineRecipe({
    slug: "tribe-mini-app",
    name: "Tribe Mini App",
    description:
      "Social copy-trading mini app on Base and Farcaster — mirror LP strategies on Uniswap V3 and Aerodrome.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Community",
    ecosystems: ["Base"],
    apis: [
      { slug: "privy", name: "Privy" },
      { slug: "hyperliquid", name: "Hyperliquid" },
      { slug: "alchemy", name: "Alchemy" },
    ],
    techStack: [
      "Next.js",
      "Farcaster Mini Apps",
      "Wagmi",
      "Viem",
      "Uniswap V3",
      "Aerodrome",
    ],
    logoSlug: "farcaster",
    githubUrl: "https://github.com/zakkycrypt01/tribe-miniapp",
    docsUrl: "https://docs.base.org/mini-apps",
    sourceUrl: "https://github.com/zakkycrypt01/tribe-miniapp",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/zakkycrypt01/tribe-miniapp" },
      { label: "Live App", url: "https://tribe-miniapp.vercel.app" },
      { label: "Farcaster Mini App", url: "https://farcaster.xyz/miniapps/CsZEN0niiZAz/tribe" },
    ],
    gettingStartedLinks: [
      { label: "README", url: "https://github.com/zakkycrypt01/tribe-miniapp#readme" },
      { label: "Base Mini Apps", url: "https://docs.base.org/mini-apps" },
    ],
    relatedRecipeSlugs: [
      "base-social-mini-app",
      "hyperliquid-copy-trading-bot",
      "hey-social-app",
      "uniswap-pool-explorer",
    ],
  }),
  defineRecipe({
    slug: "sui-kiosk-marketplace",
    name: "Sui Kiosk Marketplace",
    description:
      "Trade digital assets on Sui using Kiosk primitives — list, buy, and transfer NFT-like objects on-chain.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["infrastructure", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Sui",
    ecosystems: ["Sui"],
    apis: [{ slug: "pyth", name: "Pyth" }],
    techStack: ["Move", "Sui Kiosk", "Sui SDK", "TypeScript"],
    logoSlug: "sui",
    githubUrl: "https://github.com/MystenLabs/sui/tree/main/dapps/kiosk",
    docsUrl: "https://docs.sui.io/standards/kiosk",
    sourceUrl: "https://github.com/MystenLabs/sui/tree/main/dapps/kiosk",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "Kiosk Demo", url: "https://github.com/MystenLabs/sui/tree/main/dapps/kiosk" },
      { label: "Kiosk Docs", url: "https://docs.sui.io/standards/kiosk" },
    ],
    gettingStartedLinks: [
      { label: "Kiosk Standard", url: "https://docs.sui.io/standards/kiosk" },
    ],
    relatedRecipeSlugs: ["thirdweb-nft-marketplace", "portfolio-tracker"],
  }),
  defineRecipe({
    slug: "web3-security-bounty-tracker",
    name: "Bug Bounty Tracker",
    description:
      "Open-source dashboard for triaging Immunefi submissions and coordinating researcher payouts.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "Open Source GitHub Projects",
    ecosystems: ["Ethereum", "Arbitrum"],
    apis: [
      { slug: "immunefi", name: "Immunefi" },
      { slug: "supabase", name: "Supabase" },
    ],
    techStack: ["Next.js", "Supabase", "TypeScript"],
    logoSlug: "immunefi",
    githubUrl: "https://github.com/supabase/supabase",
    docsUrl: "https://immunefi.com/bug-bounty/",
    sourceUrl: "https://immunefi.com/bug-bounty/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "Immunefi", url: "https://immunefi.com/bug-bounty/" },
      { label: "Supabase", url: "https://supabase.com/docs" },
    ],
    gettingStartedLinks: [
      { label: "Launch a Bounty", url: "https://immunefi.com/bug-bounty/" },
    ],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "portfolio-tracker"],
  }),
  defineRecipe({
    slug: "uniswap-swap-widget",
    name: "Uniswap Swap Widget",
    description:
      "Drop-in swap widget to embed token trading inside any website or dashboard.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["trading", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Uniswap",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum", "Base"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["Uniswap Widgets", "React", "Viem", "TypeScript"],
    logoSlug: "uniswap",
    githubUrl: "https://github.com/Uniswap/widgets",
    docsUrl: "https://docs.uniswap.org/sdk/v4/overview",
    sourceUrl: "https://github.com/Uniswap/widgets",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Uniswap/widgets" },
      { label: "Uniswap Docs", url: "https://docs.uniswap.org/" },
    ],
    gettingStartedLinks: [
      { label: "Embed the Widget", url: "https://github.com/Uniswap/widgets/tree/main/examples" },
    ],
    relatedRecipeSlugs: ["defi-lending-app", "uniswap-pool-explorer"],
  }),
  defineRecipe({
    slug: "uniswap-pool-explorer",
    name: "Uniswap Pool Explorer",
    description:
      "Analytics app for tracking liquidity pools, volume, and token pairs across Uniswap deployments.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["analytics", "trading"],
    sourceType: "demo-app",
    sourceLabel: "Uniswap",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum", "Base"],
    apis: [
      { slug: "the-graph", name: "The Graph" },
      { slug: "alchemy", name: "Alchemy" },
    ],
    techStack: ["React", "GraphQL", "Subgraph", "TypeScript"],
    logoSlug: "uniswap",
    githubUrl: "https://github.com/Uniswap/info",
    docsUrl: "https://docs.uniswap.org/",
    sourceUrl: "https://github.com/Uniswap/info",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Uniswap/info" },
      { label: "Uniswap Docs", url: "https://docs.uniswap.org/" },
    ],
    gettingStartedLinks: [
      { label: "Run Locally", url: "https://github.com/Uniswap/info#readme" },
    ],
    relatedRecipeSlugs: ["defi-analytics-dashboard", "portfolio-tracker", "defi-lending-app"],
  }),
  defineRecipe({
    slug: "ens-manager-app",
    name: "ENS Manager App",
    description:
      "Register, renew, and manage .eth names with records, subnames, and reverse resolution.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["wallets", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "ENS",
    ecosystems: ["Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "ENSjs", "Viem", "TypeScript"],
    logoSlug: "ens",
    githubUrl: "https://github.com/ensdomains/ens-app-v3",
    docsUrl: "https://docs.ens.domains/",
    sourceUrl: "https://github.com/ensdomains/ens-app-v3",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/ensdomains/ens-app-v3" },
      { label: "ENS Docs", url: "https://docs.ens.domains/" },
    ],
    gettingStartedLinks: [
      { label: "App README", url: "https://github.com/ensdomains/ens-app-v3#readme" },
    ],
    relatedRecipeSlugs: ["safe-wallet-web", "onchain-commerce-shop"],
  }),
  defineRecipe({
    slug: "farcaster-mint-frame",
    name: "Farcaster Mint Frame",
    description:
      "In-feed NFT mint experience — users mint directly from a Farcaster frame without leaving the cast.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "gaming"],
    sourceType: "demo-app",
    sourceLabel: "Farcaster",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: ["Farcaster Frames", "Next.js", "OnchainKit", "TypeScript"],
    logoSlug: "farcaster",
    githubUrl: "https://github.com/coinbase/onchain-app-template",
    docsUrl: "https://docs.farcaster.xyz/",
    sourceUrl: "https://github.com/coinbase/onchain-app-template",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/coinbase/onchain-app-template" },
      { label: "Farcaster Docs", url: "https://docs.farcaster.xyz/" },
    ],
    gettingStartedLinks: [
      { label: "Frame Template", url: "https://github.com/coinbase/onchain-app-template#readme" },
    ],
    relatedRecipeSlugs: ["base-social-mini-app", "thirdweb-nft-marketplace", "hey-social-app"],
  }),
  defineRecipe({
    slug: "hey-social-app",
    name: "Hey Social App",
    description:
      "Decentralized social network with profiles, feeds, groups, and on-chain tipping on Lens.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["infrastructure", "gaming"],
    sourceType: "demo-app",
    sourceLabel: "Lens",
    ecosystems: ["Polygon"],
    apis: [{ slug: "privy", name: "Privy" }],
    techStack: ["Lens Protocol", "React", "GraphQL", "TypeScript"],
    logoSlug: "lens",
    githubUrl: "https://github.com/heyverse/hey",
    docsUrl: "https://docs.lens.xyz/",
    sourceUrl: "https://github.com/heyverse/hey",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/heyverse/hey" },
      { label: "Lens Docs", url: "https://docs.lens.xyz/" },
    ],
    gettingStartedLinks: [
      { label: "Self-Host Hey", url: "https://github.com/heyverse/hey#readme" },
    ],
    relatedRecipeSlugs: ["farcaster-mint-frame", "xmtp-messaging-agent", "tribe-mini-app"],
  }),
  defineRecipe({
    slug: "safe-wallet-web",
    name: "Safe Multisig Wallet",
    description:
      "Production multisig wallet UI for creating Safes, proposing transactions, and co-signing treasury ops.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["wallets", "payments"],
    sourceType: "demo-app",
    sourceLabel: "Safe",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum", "Base"],
    apis: [{ slug: "walletconnect", name: "WalletConnect" }],
    techStack: ["Safe{Wallet}", "React", "TypeScript", "Viem"],
    logoSlug: "safe",
    githubUrl: "https://github.com/safe-global/safe-wallet-web",
    docsUrl: "https://docs.safe.global/",
    sourceUrl: "https://github.com/safe-global/safe-wallet-web",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/safe-global/safe-wallet-web" },
      { label: "Safe Docs", url: "https://docs.safe.global/" },
    ],
    gettingStartedLinks: [
      { label: "Run the Wallet", url: "https://github.com/safe-global/safe-wallet-web#readme" },
    ],
    relatedRecipeSlugs: ["ens-manager-app", "payroll-dashboard", "automated-mass-payouts"],
  }),
  defineRecipe({
    slug: "moralis-nft-drop-app",
    name: "NFT Drop Launchpad",
    description:
      "Launch timed NFT drops with allowlists, reveal mechanics, and wallet-gated mint pages.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["wallets", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Moralis",
    ecosystems: ["Ethereum", "Polygon", "Avalanche", "Arbitrum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["Moralis SDK", "React", "Solidity", "Ethers"],
    logoSlug: "moralis",
    githubUrl: "https://github.com/nftfy/nftfy-app",
    docsUrl: "https://docs.moralis.com/",
    sourceUrl: "https://github.com/nftfy/nftfy-app",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/nftfy/nftfy-app" },
      { label: "Moralis Docs", url: "https://docs.moralis.com/" },
    ],
    gettingStartedLinks: [
      { label: "Deploy a Drop", url: "https://github.com/nftfy/nftfy-app#readme" },
    ],
    relatedRecipeSlugs: ["thirdweb-nft-marketplace", "alchemy-nft-gallery", "farcaster-mint-frame"],
  }),
  defineRecipe({
    slug: "pangolin-dex",
    name: "Pangolin DEX",
    description:
      "Full decentralized exchange interface for swapping and providing liquidity on Avalanche.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Avalanche",
    ecosystems: ["Avalanche"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Uniswap V2", "Solidity", "TypeScript"],
    logoSlug: "avalanche",
    githubUrl: "https://github.com/pangolindex/interface",
    docsUrl: "https://docs.avax.network/",
    sourceUrl: "https://github.com/pangolindex/interface",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/pangolindex/interface" },
      { label: "Avalanche Docs", url: "https://docs.avax.network/" },
    ],
    gettingStartedLinks: [
      { label: "Run the DEX UI", url: "https://github.com/pangolindex/interface#readme" },
    ],
    relatedRecipeSlugs: ["uniswap-swap-widget", "quickswap-dex"],
  }),
  defineRecipe({
    slug: "thala-defi-app",
    name: "Thala DeFi App",
    description:
      "Move-based DeFi app on Aptos for swapping stablecoins, staking, and managing vault positions.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Aptos",
    ecosystems: ["Aptos"],
    apis: [{ slug: "pyth", name: "Pyth" }],
    techStack: ["Move", "Aptos SDK", "React", "TypeScript"],
    logoSlug: "aptos",
    githubUrl: "https://github.com/ThalaLabs/thala-dapp",
    docsUrl: "https://aptos.dev/",
    sourceUrl: "https://github.com/ThalaLabs/thala-dapp",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/ThalaLabs/thala-dapp" },
      { label: "Aptos Docs", url: "https://aptos.dev/" },
    ],
    gettingStartedLinks: [
      { label: "Thala App", url: "https://github.com/ThalaLabs/thala-dapp#readme" },
    ],
    relatedRecipeSlugs: ["sui-kiosk-marketplace", "defi-lending-app"],
  }),
  defineRecipe({
    slug: "jediswap-dex",
    name: "JediSwap DEX",
    description:
      "Starknet AMM interface for swapping tokens and managing liquidity positions on L2.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Starknet",
    ecosystems: ["Starknet"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Starknet.js", "Cairo", "TypeScript"],
    logoSlug: "starknet",
    githubUrl: "https://github.com/jediswaplabs/jediswap-interface",
    docsUrl: "https://docs.starknet.io/",
    sourceUrl: "https://github.com/jediswaplabs/jediswap-interface",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/jediswaplabs/jediswap-interface" },
      { label: "Starknet Docs", url: "https://docs.starknet.io/" },
    ],
    gettingStartedLinks: [
      { label: "Run JediSwap", url: "https://github.com/jediswaplabs/jediswap-interface#readme" },
    ],
    relatedRecipeSlugs: ["uniswap-swap-widget", "pangolin-dex"],
  }),
  defineRecipe({
    slug: "quickswap-dex",
    name: "QuickSwap DEX",
    description:
      "Polygon DEX frontend for token swaps, liquidity pools, and yield farming dashboards.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Polygon",
    ecosystems: ["Polygon"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Uniswap V2", "Solidity", "TypeScript"],
    logoSlug: "polygon",
    githubUrl: "https://github.com/QuickSwapExchange/interface-v2",
    docsUrl: "https://docs.polygon.technology/",
    sourceUrl: "https://github.com/QuickSwapExchange/interface-v2",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/QuickSwapExchange/interface-v2" },
      { label: "Polygon Docs", url: "https://docs.polygon.technology/" },
    ],
    gettingStartedLinks: [
      { label: "Run QuickSwap UI", url: "https://github.com/QuickSwapExchange/interface-v2#readme" },
    ],
    relatedRecipeSlugs: ["hey-social-app", "uniswap-pool-explorer", "pangolin-dex"],
  }),
  ...recipeCatalogAdditionInputs.map(defineRecipe),
];
