import type { RecipeEntry } from "./recipe-directory-types";

type RecipeInput = Omit<
  RecipeEntry,
  "links" | "gettingStartedLinks" | "relatedRecipeSlugs" | "techStack" | "screenshots"
> & {
  techStack?: string[];
  screenshots?: string[];
  links?: RecipeEntry["links"];
  gettingStartedLinks?: RecipeEntry["gettingStartedLinks"];
  relatedRecipeSlugs?: string[];
};

function recipe(input: RecipeInput): RecipeInput {
  return input;
}

/** Open-source starters, demos, and curated collections for /recipes */
export const recipeCatalogAdditionInputs: RecipeInput[] = [
  // Farcaster Mini Apps
  recipe({
    slug: "farcaster-mini-app-full-demo",
    name: "Farcaster Mini App Full Demo",
    description:
      "End-to-end Farcaster mini app template from Base demos with wallet context and onchain actions.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["Farcaster SDK", "Next.js", "Mini Apps", "OnchainKit"],
    logoSlug: "farcaster",
    githubUrl:
      "https://github.com/base/demos/tree/master/mini-apps/templates/farcaster-sdk/mini-app-full-demo",
    sourceUrl:
      "https://github.com/base/demos/tree/master/mini-apps/templates/farcaster-sdk/mini-app-full-demo",
    docsUrl: "https://docs.farcaster.xyz/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/base/demos/tree/master/mini-apps/templates/farcaster-sdk/mini-app-full-demo",
      },
      { label: "Farcaster Docs", url: "https://docs.farcaster.xyz/" },
    ],
    gettingStartedLinks: [
      {
        label: "Base Demos",
        url: "https://github.com/base/demos",
      },
    ],
    relatedRecipeSlugs: ["farcaster-miniapps-sdk", "base-minikit-starter"],
  }),
  recipe({
    slug: "base-minikit-starter",
    name: "Base MiniKit Starter",
    description:
      "Starter repo for building Farcaster mini apps on Base with MiniKit from builders-garden.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "builders-garden",
    ecosystems: ["Base"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["MiniKit", "Next.js", "Farcaster Mini Apps", "Base"],
    logoSlug: "base",
    githubUrl: "https://github.com/builders-garden/base-minikit-starter",
    sourceUrl: "https://github.com/builders-garden/base-minikit-starter",
    docsUrl: "https://docs.base.org/mini-apps",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/builders-garden/base-minikit-starter",
      },
    ],
    gettingStartedLinks: [
      {
        label: "README",
        url: "https://github.com/builders-garden/base-minikit-starter#readme",
      },
    ],
    relatedRecipeSlugs: ["farcaster-mini-app-full-demo", "base-mini-app-starter-patnir"],
  }),
  recipe({
    slug: "base-mini-app-starter-patnir",
    name: "Base Mini App Starter",
    description:
      "Minimal starter for shipping a Farcaster mini app on Base with wallet and frame hooks.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "patnir",
    ecosystems: ["Base"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["Next.js", "Farcaster Mini Apps", "TypeScript"],
    logoSlug: "base",
    githubUrl: "https://github.com/patnir/starterminiapp",
    sourceUrl: "https://github.com/patnir/starterminiapp",
    docsUrl: "https://docs.base.org/mini-apps",
    isOpenSource: true,
    isFree: true,
    links: [{ label: "GitHub", url: "https://github.com/patnir/starterminiapp" }],
    gettingStartedLinks: [
      { label: "README", url: "https://github.com/patnir/starterminiapp#readme" },
    ],
    relatedRecipeSlugs: ["base-minikit-starter", "farcaster-mini-app-full-demo"],
  }),
  recipe({
    slug: "farcaster-miniapps-sdk",
    name: "Farcaster Mini Apps SDK + Examples",
    description:
      "Official Farcaster mini apps monorepo with SDK packages and reference implementations.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "Farcaster",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["Farcaster Mini Apps", "TypeScript", "React"],
    logoSlug: "farcaster",
    githubUrl: "https://github.com/farcasterxyz/miniapps",
    sourceUrl: "https://github.com/farcasterxyz/miniapps",
    docsUrl: "https://docs.farcaster.xyz/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/farcasterxyz/miniapps" },
      { label: "Farcaster Docs", url: "https://docs.farcaster.xyz/" },
    ],
    gettingStartedLinks: [
      { label: "Repository", url: "https://github.com/farcasterxyz/miniapps#readme" },
    ],
    relatedRecipeSlugs: ["farcaster-mini-app-full-demo", "awesome-farcaster-dev"],
  }),
  recipe({
    slug: "awesome-farcaster-dev",
    name: "Awesome Farcaster Dev",
    description:
      "Community-curated list of open-source Farcaster tools, SDKs, and example projects.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "FTCHD",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["Curated List", "Farcaster"],
    logoSlug: "farcaster",
    githubUrl: "https://github.com/FTCHD/awesome-farcaster-dev",
    sourceUrl: "https://github.com/FTCHD/awesome-farcaster-dev",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/FTCHD/awesome-farcaster-dev" },
    ],
    relatedRecipeSlugs: ["awesome-farcaster-a16z", "farcaster-miniapps-sdk"],
  }),

  // Coinbase / Base
  recipe({
    slug: "base-demos",
    name: "Base Demos",
    description:
      "Collection of demo apps from Base — mini apps, paymaster examples, and account-abstraction flows.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "ai"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "coinbase-agentkit", name: "Coinbase AgentKit" }],
    techStack: ["Base", "Mini Apps", "Paymaster", "Smart Accounts"],
    logoSlug: "base",
    githubUrl: "https://github.com/base/demos",
    sourceUrl: "https://github.com/base/demos",
    docsUrl: "https://docs.base.org/",
    isOpenSource: true,
    isFree: true,
    links: [{ label: "GitHub", url: "https://github.com/base/demos" }],
    gettingStartedLinks: [
      { label: "Browse Demos", url: "https://github.com/base/demos#readme" },
    ],
    relatedRecipeSlugs: ["hangman-onchain", "agent-spend-permissions", "agentkit"],
  }),
  recipe({
    slug: "hangman-onchain",
    name: "Hangman Onchain",
    description:
      "Onchain hangman game demo using Base paymaster sponsorship for gasless gameplay.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["gaming", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "pimlico", name: "Pimlico" }],
    techStack: ["Paymaster", "Base", "Smart Accounts", "React"],
    logoSlug: "base",
    githubUrl:
      "https://github.com/base/demos/tree/master/paymaster/hangman-onchain",
    sourceUrl:
      "https://github.com/base/demos/tree/master/paymaster/hangman-onchain",
    docsUrl: "https://docs.base.org/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/base/demos/tree/master/paymaster/hangman-onchain",
      },
    ],
    relatedRecipeSlugs: ["base-demos", "agent-spend-permissions"],
  }),
  recipe({
    slug: "agent-spend-permissions",
    name: "Agent Spend Permissions",
    description:
      "Demo of Base Account agent spend permissions for controlled autonomous transactions.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["ai", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "coinbase-agentkit", name: "Coinbase AgentKit" }],
    techStack: ["AgentKit", "Base Account", "Spend Permissions", "TypeScript"],
    logoSlug: "coinbase",
    githubUrl:
      "https://github.com/base/demos/tree/master/base-account/agent-spend-permissions",
    sourceUrl:
      "https://github.com/base/demos/tree/master/base-account/agent-spend-permissions",
    docsUrl: "https://docs.cdp.coinbase.com/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/base/demos/tree/master/base-account/agent-spend-permissions",
      },
    ],
    relatedRecipeSlugs: ["agentkit", "onchain-agent-demo", "base-demos"],
  }),

  // Ethereum / EVM Starters
  recipe({
    slug: "scaffold-eth-2",
    name: "Scaffold-ETH 2",
    description:
      "Full-stack Ethereum starter with Hardhat, React, and contract hot-reload for rapid dapp builds.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "Scaffold-ETH",
    ecosystems: ["Ethereum", "Base"],
    apis: [{ slug: "scaffold-eth", name: "Scaffold-ETH" }],
    techStack: ["Hardhat", "Next.js", "Wagmi", "Viem"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/scaffold-eth/scaffold-eth-2",
    sourceUrl: "https://github.com/scaffold-eth/scaffold-eth-2",
    docsUrl: "https://docs.scaffoldeth.io/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/scaffold-eth/scaffold-eth-2" },
      { label: "Documentation", url: "https://docs.scaffoldeth.io/" },
    ],
    gettingStartedLinks: [
      { label: "Quick Start", url: "https://github.com/scaffold-eth/scaffold-eth-2#readme" },
    ],
    relatedRecipeSlugs: ["scaffold-base", "developer-dao-web3-starter-kits"],
  }),
  recipe({
    slug: "scaffold-base",
    name: "Scaffold Base",
    description: "Base-ready fork of Scaffold-ETH for L2-native dapp prototyping.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "BuidlGuidl",
    ecosystems: ["Base"],
    apis: [{ slug: "scaffold-eth", name: "Scaffold-ETH" }],
    techStack: ["Scaffold-ETH", "Base", "Wagmi", "Hardhat"],
    logoSlug: "base",
    githubUrl: "https://github.com/BuidlGuidl/scaffold-base",
    sourceUrl: "https://github.com/BuidlGuidl/scaffold-base",
    docsUrl: "https://docs.base.org/",
    isOpenSource: true,
    isFree: true,
    links: [{ label: "GitHub", url: "https://github.com/BuidlGuidl/scaffold-base" }],
    relatedRecipeSlugs: ["scaffold-eth-2", "base-demos"],
  }),
  recipe({
    slug: "developer-dao-web3-starter-kits",
    name: "Developer DAO Web3 Starter Kits",
    description:
      "Collection of starter kits maintained by Developer DAO for common Web3 app patterns.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "Developer DAO",
    ecosystems: ["Ethereum", "Base"],
    apis: [{ slug: "wagmi", name: "Wagmi" }],
    techStack: ["Starter Kits", "React", "Solidity", "TypeScript"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/Developer-DAO/web3-starter-kits",
    sourceUrl: "https://github.com/Developer-DAO/web3-starter-kits",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/Developer-DAO/web3-starter-kits",
      },
    ],
    relatedRecipeSlugs: ["scaffold-eth-2", "useweb3-starter-kits"],
  }),

  // DeFi Protocol Interfaces
  recipe({
    slug: "uniswap-interface",
    name: "Uniswap Interface",
    description:
      "Production-grade open-source frontend for swapping, pooling, and governance on Uniswap.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Uniswap",
    ecosystems: ["Ethereum", "Base", "Arbitrum"],
    apis: [{ slug: "uniswap-sdk", name: "Uniswap SDK" }],
    techStack: ["React", "Uniswap SDK", "TypeScript", "Viem"],
    logoSlug: "uniswap",
    githubUrl: "https://github.com/Uniswap/interface",
    sourceUrl: "https://github.com/Uniswap/interface",
    docsUrl: "https://docs.uniswap.org/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Uniswap/interface" },
      { label: "Uniswap Docs", url: "https://docs.uniswap.org/" },
    ],
    relatedRecipeSlugs: ["uniswap-swap-widget", "uniswap-pool-explorer"],
  }),
  recipe({
    slug: "aave-interface",
    name: "Aave Interface",
    description:
      "Official Aave frontend for supplying, borrowing, and monitoring positions across markets.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Aave",
    ecosystems: ["Ethereum", "Base", "Arbitrum"],
    apis: [{ slug: "aave-sdk", name: "Aave SDK" }],
    techStack: ["React", "Aave SDK", "TypeScript", "GraphQL"],
    logoSlug: "aave",
    githubUrl: "https://github.com/aave/interface",
    sourceUrl: "https://github.com/aave/interface",
    docsUrl: "https://aave.com/docs",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/aave/interface" },
      { label: "Aave Docs", url: "https://aave.com/docs" },
    ],
    relatedRecipeSlugs: ["defi-lending-app", "uniswap-interface"],
  }),
  recipe({
    slug: "balancer-frontend-v3",
    name: "Balancer Frontend",
    description:
      "Balancer v3 web app for weighted pools, swaps, and liquidity management dashboards.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "demo-app",
    sourceLabel: "Balancer",
    ecosystems: ["Ethereum", "Arbitrum"],
    apis: [{ name: "Balancer" }],
    techStack: ["React", "Balancer SDK", "TypeScript"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/balancer/frontend-v3",
    sourceUrl: "https://github.com/balancer/frontend-v3",
    docsUrl: "https://docs.balancer.fi/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/balancer/frontend-v3" },
      { label: "Balancer Docs", url: "https://docs.balancer.fi/" },
    ],
    relatedRecipeSlugs: ["uniswap-interface", "aave-interface"],
  }),

  // Solana
  recipe({
    slug: "solana-dapp-scaffold",
    name: "Solana dApp Scaffold",
    description:
      "Official Solana dApp scaffold with wallet connection and client-side program hooks.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "Solana Labs",
    ecosystems: ["Solana"],
    apis: [{ slug: "solana", name: "Solana" }],
    techStack: ["React", "Solana Web3.js", "Wallet Adapter"],
    logoSlug: "solana",
    githubUrl: "https://github.com/solana-labs/dapp-scaffold",
    sourceUrl: "https://github.com/solana-labs/dapp-scaffold",
    docsUrl: "https://solana.com/developers",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/solana-labs/dapp-scaffold" },
    ],
    relatedRecipeSlugs: ["solana-wallet-adapter", "anchor-nextjs-counter"],
  }),
  recipe({
    slug: "anchor-nextjs-counter",
    name: "Anchor + Next.js Counter",
    description:
      "Counter program template using Anchor on Solana with a Next.js frontend and Web3.js client.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure"],
    sourceType: "template",
    sourceLabel: "Solana Developers",
    ecosystems: ["Solana"],
    apis: [{ slug: "anchor", name: "Anchor" }],
    techStack: ["Anchor", "Next.js", "Solana Web3.js", "Rust"],
    logoSlug: "solana",
    githubUrl: "https://github.com/solana-developers/anchor-web3js-nextjs",
    sourceUrl: "https://github.com/solana-developers/anchor-web3js-nextjs",
    docsUrl: "https://www.anchor-lang.com/docs",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/solana-developers/anchor-web3js-nextjs",
      },
    ],
    relatedRecipeSlugs: ["solana-dapp-scaffold", "solana-web3-examples"],
  }),
  recipe({
    slug: "solana-web3-examples",
    name: "Solana Web3 Examples",
    description:
      "Example scripts and snippets for common Solana client patterns with Web3.js.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "Solana Developers",
    ecosystems: ["Solana"],
    apis: [{ slug: "helius", name: "Helius" }],
    techStack: ["Solana Web3.js", "TypeScript", "Examples"],
    logoSlug: "solana",
    githubUrl: "https://github.com/solana-developers/web3-examples",
    sourceUrl: "https://github.com/solana-developers/web3-examples",
    docsUrl: "https://solana.com/developers",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/solana-developers/web3-examples" },
    ],
    relatedRecipeSlugs: ["anchor-nextjs-counter", "solana-wallet-adapter"],
  }),
  recipe({
    slug: "solana-wallet-adapter",
    name: "Solana Wallet Adapter",
    description:
      "Modular wallet connection library for Solana dApps with React and vanilla JS bindings.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["wallets"],
    sourceType: "github",
    sourceLabel: "Anza",
    ecosystems: ["Solana"],
    apis: [{ slug: "solana", name: "Solana" }],
    techStack: ["Wallet Adapter", "React", "Solana Web3.js"],
    logoSlug: "solana",
    githubUrl: "https://github.com/anza-xyz/wallet-adapter",
    sourceUrl: "https://github.com/anza-xyz/wallet-adapter",
    docsUrl: "https://github.com/anza-xyz/wallet-adapter#readme",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/anza-xyz/wallet-adapter" },
    ],
    relatedRecipeSlugs: ["solana-dapp-scaffold", "solana-pay-sdk"],
  }),
  recipe({
    slug: "solana-pay-sdk",
    name: "Solana Pay",
    description:
      "Official Solana Pay protocol repo for QR payments, transaction requests, and checkout flows.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["payments"],
    sourceType: "github",
    sourceLabel: "Anza",
    ecosystems: ["Solana"],
    apis: [{ slug: "solana", name: "Solana" }],
    techStack: ["Solana Pay", "QR Codes", "Solana Web3.js"],
    logoSlug: "solana",
    githubUrl: "https://github.com/anza-xyz/solana-pay",
    sourceUrl: "https://github.com/anza-xyz/solana-pay",
    docsUrl: "https://docs.solanapay.com/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/anza-xyz/solana-pay" },
      { label: "Solana Pay Docs", url: "https://docs.solanapay.com/" },
    ],
    relatedRecipeSlugs: ["solana-pay-store", "solana-wallet-adapter"],
  }),

  // DAO & Governance
  recipe({
    slug: "snapshot-interface",
    name: "Snapshot Interface",
    description:
      "Open-source governance UI for off-chain voting with on-chain execution via Snapshot spaces.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Snapshot",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum"],
    apis: [{ name: "Snapshot" }],
    techStack: ["Vue", "IPFS", "Governance", "TypeScript"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/snapshot-labs/snapshot-v1",
    sourceUrl: "https://github.com/snapshot-labs/snapshot-v1",
    docsUrl: "https://docs.snapshot.box/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/snapshot-labs/snapshot-v1" },
      { label: "Snapshot Docs", url: "https://docs.snapshot.box/" },
    ],
    relatedRecipeSlugs: ["tally-zero", "awesome-web3-projects"],
  }),
  recipe({
    slug: "tally-zero",
    name: "Tally Zero",
    description:
      "Decentralized voting application from Tally for onchain governor proposals and delegation.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Tally",
    ecosystems: ["Ethereum", "Arbitrum"],
    apis: [{ name: "Tally" }],
    techStack: ["React", "Governance", "Onchain Voting", "TypeScript"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/withtally/tally-zero",
    sourceUrl: "https://github.com/withtally/tally-zero",
    docsUrl: "https://docs.tally.xyz/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/withtally/tally-zero" },
      { label: "Tally Docs", url: "https://docs.tally.xyz/" },
    ],
    relatedRecipeSlugs: ["snapshot-interface"],
  }),
  recipe({
    slug: "awesome-web3-projects",
    name: "Awesome Web3 Projects",
    description:
      "Curated GitHub list of Web3 projects, tools, and starter repos across ecosystems.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "Community",
    ecosystems: ["Ethereum", "Solana", "Base"],
    apis: [],
    techStack: ["Curated List", "Open Source"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/Shubham0850/awesome-web3-projects",
    sourceUrl: "https://github.com/Shubham0850/awesome-web3-projects",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/Shubham0850/awesome-web3-projects",
      },
    ],
    relatedRecipeSlugs: ["awesome-farcaster-dev", "useweb3-starter-kits"],
  }),

  // Thirdweb Templates
  recipe({
    slug: "thirdweb-all-templates",
    name: "Thirdweb All Templates",
    description:
      "GitHub organization of example apps — NFT drops, marketplaces, auth, and payments templates.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "thirdweb",
    ecosystems: ["Ethereum", "Base", "Polygon"],
    apis: [{ name: "thirdweb" }],
    techStack: ["thirdweb SDK", "Next.js", "Solidity"],
    logoSlug: "thirdweb",
    githubUrl: "https://github.com/orgs/thirdweb-example/repositories",
    sourceUrl: "https://github.com/orgs/thirdweb-example/repositories",
    docsUrl: "https://portal.thirdweb.com/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "All Repositories",
        url: "https://github.com/orgs/thirdweb-example/repositories",
      },
    ],
    relatedRecipeSlugs: ["thirdweb-template-explorer", "thirdweb-nft-marketplace"],
  }),
  recipe({
    slug: "thirdweb-template-explorer",
    name: "Thirdweb Template Explorer",
    description:
      "Browse and deploy thirdweb templates for NFTs, commerce, and wallet login from the portal.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "template",
    sourceLabel: "thirdweb",
    ecosystems: ["Ethereum", "Base", "Polygon"],
    apis: [{ name: "thirdweb" }],
    techStack: ["thirdweb", "Templates", "No-code Deploy"],
    logoSlug: "thirdweb",
    sourceUrl: "https://thirdweb.com/templates",
    docsUrl: "https://portal.thirdweb.com/templates",
    isOpenSource: false,
    isFree: true,
    links: [
      { label: "Template Explorer", url: "https://thirdweb.com/templates" },
      { label: "Portal Docs", url: "https://portal.thirdweb.com/templates" },
    ],
    gettingStartedLinks: [
      { label: "Browse Templates", url: "https://thirdweb.com/templates" },
    ],
    relatedRecipeSlugs: ["thirdweb-all-templates", "thirdweb-nft-marketplace"],
  }),

  // Curated Collections
  recipe({
    slug: "awesome-farcaster-a16z",
    name: "Awesome Farcaster",
    description:
      "a16z-maintained list of Farcaster clients, tools, frames, and developer resources.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "a16z",
    ecosystems: ["Base", "Ethereum"],
    apis: [{ slug: "farcaster", name: "Farcaster" }],
    techStack: ["Curated List", "Farcaster"],
    logoSlug: "farcaster",
    githubUrl: "https://github.com/a16z/awesome-farcaster",
    sourceUrl: "https://github.com/a16z/awesome-farcaster",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/a16z/awesome-farcaster" },
    ],
    relatedRecipeSlugs: ["awesome-farcaster-dev", "farcaster-miniapps-sdk"],
  }),
  recipe({
    slug: "useweb3-starter-kits",
    name: "useWeb3 Starter Kits",
    description:
      "Curated directory of Web3 starter kits, tutorials, and example projects across stacks.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "documentation",
    sourceLabel: "useWeb3",
    ecosystems: ["Ethereum", "Solana", "Base"],
    apis: [],
    techStack: ["Curated Directory", "Starter Kits"],
    logoSlug: "ethereum",
    sourceUrl: "https://www.useweb3.xyz/starter-kits",
    docsUrl: "https://www.useweb3.xyz/starter-kits",
    isOpenSource: false,
    isFree: true,
    links: [
      { label: "Starter Kits", url: "https://www.useweb3.xyz/starter-kits" },
    ],
    gettingStartedLinks: [
      { label: "Browse Kits", url: "https://www.useweb3.xyz/starter-kits" },
    ],
    relatedRecipeSlugs: ["developer-dao-web3-starter-kits", "awesome-web3-projects"],
  }),

  // Community-built apps (individual devs & small teams)
  recipe({
    slug: "xmtp-inbox-wallet-dm",
    name: "XMTP Inbox",
    description:
      "Community wallet-to-wallet chat app built on XMTP for encrypted DMs between addresses.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "wallet-dm",
    ecosystems: ["Ethereum", "Base"],
    apis: [{ slug: "xmtp", name: "XMTP" }],
    techStack: ["XMTP", "React", "Wallet DMs"],
    logoSlug: "xmtp",
    githubUrl: "https://github.com/wallet-dm/xmtp-dapp",
    sourceUrl: "https://github.com/wallet-dm/xmtp-dapp",
    docsUrl: "https://docs.xmtp.org/",
    isOpenSource: true,
    isFree: true,
    links: [{ label: "GitHub", url: "https://github.com/wallet-dm/xmtp-dapp" }],
    relatedRecipeSlugs: ["chatter-xmtp-privy", "xmtp-messaging-agent"],
  }),
  recipe({
    slug: "chatter-xmtp-privy",
    name: "Chatter",
    description:
      "XMTP chat app template using Next.js and Privy for wallet login and messaging.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "turbo-eth",
    ecosystems: ["Ethereum", "Base"],
    apis: [
      { slug: "xmtp", name: "XMTP" },
      { slug: "privy", name: "Privy" },
    ],
    techStack: ["XMTP", "Next.js", "Privy", "TypeScript"],
    logoSlug: "xmtp",
    githubUrl: "https://github.com/turbo-eth/template-xmtp-app",
    sourceUrl: "https://github.com/turbo-eth/template-xmtp-app",
    docsUrl: "https://docs.xmtp.org/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/turbo-eth/template-xmtp-app" },
    ],
    relatedRecipeSlugs: ["xmtp-inbox-wallet-dm", "xmtp-messaging-agent"],
  }),
  recipe({
    slug: "blockhead-explorer",
    name: "Blockhead",
    description:
      "Community portfolio tracker with DeFi positions, NFT gallery, and multi-wallet views.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["analytics", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "BunsDev",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum"],
    apis: [{ slug: "dune", name: "Dune Analytics" }],
    techStack: ["React", "DeFi", "NFT Viewer", "Portfolio"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/BunsDev/blockhead-explorer",
    sourceUrl: "https://github.com/BunsDev/blockhead-explorer",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/BunsDev/blockhead-explorer" },
    ],
    relatedRecipeSlugs: ["portfolio-tracker", "web3-wallet-analyzer"],
  }),
  recipe({
    slug: "web3-wallet-analyzer",
    name: "Web3 Wallet Analyzer",
    description:
      "Analyze any EVM wallet — token balances, portfolio value, and asset distribution charts.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["analytics", "wallets"],
    sourceType: "demo-app",
    sourceLabel: "Community",
    ecosystems: ["Ethereum", "Base", "Polygon", "Arbitrum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["Next.js", "Moralis", "Viem", "Recharts"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/khalilahmed63/web3-wallet-analyzer",
    sourceUrl: "https://github.com/khalilahmed63/web3-wallet-analyzer",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/khalilahmed63/web3-wallet-analyzer",
      },
      { label: "Live Demo", url: "https://web3-wallet-analyzer.vercel.app" },
    ],
    relatedRecipeSlugs: ["blockhead-explorer", "portfolio-tracker"],
  }),
  recipe({
    slug: "markkop-nft-marketplace",
    name: "NFT Marketplace (Markkop)",
    description:
      "Full-stack community NFT marketplace to mint, list, buy, and sell digital assets.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["infrastructure", "gaming"],
    sourceType: "demo-app",
    sourceLabel: "Markkop",
    ecosystems: ["Ethereum"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Solidity", "IPFS", "Smart Contracts"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/Markkop/nft-marketplace",
    sourceUrl: "https://github.com/Markkop/nft-marketplace",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Markkop/nft-marketplace" },
    ],
    relatedRecipeSlugs: ["thirdweb-nft-marketplace", "nft-gallery-cw3d"],
  }),
  recipe({
    slug: "nft-gallery-cw3d",
    name: "NFT Gallery",
    description:
      "View NFTs owned by a connected wallet using RainbowKit, Wagmi, and the Alchemy NFT API.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["infrastructure"],
    sourceType: "template",
    sourceLabel: "Community Fork",
    ecosystems: ["Ethereum", "Polygon", "Base"],
    apis: [
      { slug: "alchemy", name: "Alchemy" },
      { slug: "rainbowkit", name: "RainbowKit" },
    ],
    techStack: ["Next.js", "RainbowKit", "Alchemy SDK", "Wagmi"],
    logoSlug: "alchemy",
    githubUrl: "https://github.com/alchemyplatform/cw3d-nft-explorer",
    sourceUrl: "https://github.com/alchemyplatform/cw3d-nft-explorer",
    docsUrl: "https://docs.alchemy.com/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/alchemyplatform/cw3d-nft-explorer",
      },
      { label: "Create Web3 Dapp", url: "https://github.com/alchemyplatform/create-web3-dapp" },
    ],
    relatedRecipeSlugs: ["markkop-nft-marketplace", "alchemy-nft-gallery"],
  }),
  recipe({
    slug: "polymint-maadhav",
    name: "PolyMint",
    description:
      "No-code-style dapp to deploy ERC-721/1155 contracts and mint NFTs on Polygon.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "gaming"],
    sourceType: "demo-app",
    sourceLabel: "Maadhav",
    ecosystems: ["Polygon"],
    apis: [{ slug: "alchemy", name: "Alchemy" }],
    techStack: ["React", "Truffle", "IPFS", "Polygon"],
    logoSlug: "polygon",
    githubUrl: "https://github.com/Maadhav/poly-mint",
    sourceUrl: "https://github.com/Maadhav/poly-mint",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Maadhav/poly-mint" },
      { label: "Live App", url: "https://polymint.netlify.app/" },
    ],
    relatedRecipeSlugs: ["farcaster-mint-frame", "thirdweb-nft-marketplace"],
  }),
  recipe({
    slug: "web3-ai-trading-agent",
    name: "Web3 AI Trading Agent",
    description:
      "Autonomous trading agent on Base using Uniswap V4 and LLM-driven strategy execution.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["ai", "trading"],
    sourceType: "demo-app",
    sourceLabel: "Chainstack Labs",
    ecosystems: ["Base"],
    apis: [
      { slug: "coinbase-agentkit", name: "Coinbase AgentKit" },
      { slug: "uniswap-sdk", name: "Uniswap SDK" },
      { slug: "chainstack", name: "Chainstack" },
    ],
    techStack: ["Python", "Uniswap V4", "AI Agents", "Base"],
    logoSlug: "base",
    githubUrl: "https://github.com/chainstacklabs/web3-ai-trading-agent",
    sourceUrl: "https://github.com/chainstacklabs/web3-ai-trading-agent",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/chainstacklabs/web3-ai-trading-agent",
      },
    ],
    relatedRecipeSlugs: ["agentkit", "uniswap-interface", "hyperliquid-trading-bot"],
  }),
  recipe({
    slug: "web3-ethereum-defi-python",
    name: "Web3 Ethereum DeFi (Python)",
    description:
      "Python library for DeFi trading automation across Uniswap, Aave, and USDC liquidity workflows.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading"],
    sourceType: "github",
    sourceLabel: "Trading Strategy",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum"],
    apis: [
      { slug: "uniswap-sdk", name: "Uniswap SDK" },
      { slug: "aave-sdk", name: "Aave SDK" },
    ],
    techStack: ["Python", "Uniswap", "Aave", "DeFi"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/tradingstrategy-ai/web3-ethereum-defi",
    sourceUrl: "https://github.com/tradingstrategy-ai/web3-ethereum-defi",
    docsUrl: "https://web3-ethereum-defi.readthedocs.io/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/tradingstrategy-ai/web3-ethereum-defi",
      },
      {
        label: "Documentation",
        url: "https://web3-ethereum-defi.readthedocs.io/",
      },
    ],
    relatedRecipeSlugs: ["uniswap-interface", "aave-interface"],
  }),
  recipe({
    slug: "lingos-onchain-game",
    name: "Lingos",
    description:
      "Onchain phrase guessing game from Base demos with paymaster-sponsored transactions.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["gaming", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Base",
    ecosystems: ["Base"],
    apis: [{ slug: "pimlico", name: "Pimlico" }],
    techStack: ["Onchain Game", "Paymaster", "Base", "React"],
    logoSlug: "base",
    githubUrl:
      "https://github.com/base/demos/tree/master/paymaster/onchain-game-lingos",
    sourceUrl:
      "https://github.com/base/demos/tree/master/paymaster/onchain-game-lingos",
    docsUrl: "https://docs.base.org/",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/base/demos/tree/master/paymaster/onchain-game-lingos",
      },
    ],
    relatedRecipeSlugs: ["hangman-onchain", "base-demos"],
  }),
  recipe({
    slug: "solanahub-freelance-marketplace",
    name: "SolanaHub Freelance Marketplace",
    description:
      "Community freelance marketplace on Solana with milestone escrow, USDC payments, and reputation.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["payments", "infrastructure"],
    sourceType: "demo-app",
    sourceLabel: "Community",
    ecosystems: ["Solana"],
    apis: [{ slug: "helius", name: "Helius" }, { slug: "anchor", name: "Anchor" }],
    techStack: ["Anchor", "Next.js", "Escrow", "USDC"],
    logoSlug: "solana",
    githubUrl: "https://github.com/raushan728/solanahub",
    sourceUrl: "https://github.com/raushan728/solanahub",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/raushan728/solanahub" },
      { label: "Live App", url: "https://solanahub-six.vercel.app" },
    ],
    relatedRecipeSlugs: ["anchor-nextjs-counter", "solana-pay-store"],
  }),
  recipe({
    slug: "web3-privacy-now",
    name: "Web3 Privacy Now",
    description:
      "Community-maintained database of privacy tools, apps, and resources across Web3.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "web3privacy",
    ecosystems: ["Ethereum", "Polygon", "Arbitrum"],
    apis: [{ slug: "aztec", name: "Aztec" }],
    techStack: ["Curated Database", "Privacy", "Open Data"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/web3privacy/web3privacy",
    sourceUrl: "https://github.com/web3privacy/web3privacy",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/web3privacy/web3privacy" },
      { label: "Project Site", url: "https://web3privacy.info" },
    ],
    relatedRecipeSlugs: ["semaphore", "awesome-web3-ahmet"],
  }),
  recipe({
    slug: "awesome-web3-ahmet",
    name: "Awesome Web3",
    description:
      "Large community-curated list of Web3 tools, dapps, libraries, and learning resources.",
    difficulty: "beginner",
    setupTime: "15-min",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "ahmet",
    ecosystems: ["Ethereum", "Solana", "Base"],
    apis: [],
    techStack: ["Curated List", "Open Source"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/ahmet/awesome-web3",
    sourceUrl: "https://github.com/ahmet/awesome-web3",
    isOpenSource: true,
    isFree: true,
    links: [{ label: "GitHub", url: "https://github.com/ahmet/awesome-web3" }],
    relatedRecipeSlugs: ["awesome-web3-projects", "useweb3-starter-kits"],
  }),

  // Community GitHub starters (user-curated)
  recipe({
    slug: "gno-smart-contracts",
    name: "Gno & gno.land",
    description:
      "Interpreted Go smart contracts on gno.land — deterministic realms, composable packages, and Tendermint2 consensus.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["infrastructure"],
    sourceType: "github",
    sourceLabel: "gnolang",
    ecosystems: ["Ethereum"],
    apis: [],
    techStack: ["Gno", "Go", "gno.land", "Tendermint2", "Smart Contracts"],
    logoSlug: "gno",
    githubUrl: "https://github.com/gnolang/gno",
    sourceUrl: "https://github.com/gnolang/gno",
    docsUrl: "https://docs.gno.land/",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/gnolang/gno" },
      { label: "Documentation", url: "https://docs.gno.land/" },
      { label: "Playground", url: "https://play.gno.land" },
    ],
    gettingStartedLinks: [
      { label: "Getting Started", url: "https://docs.gno.land/users/interact-with-gnokey" },
      { label: "Examples", url: "https://github.com/gnolang/gno/tree/master/examples" },
    ],
    relatedRecipeSlugs: ["scaffold-eth-2", "dapp-starter-jellydn"],
  }),
  recipe({
    slug: "polymarket-trading-bot",
    name: "Polymarket Trading Bot",
    description:
      "Open-source Polymarket bot for copy trading, arbitrage, and automated prediction-market strategies.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "ai"],
    sourceType: "github",
    sourceLabel: "Trading-GPT",
    ecosystems: ["Ethereum", "Polygon"],
    apis: [],
    techStack: ["Python", "Polymarket API", "Copy Trading", "Arbitrage"],
    logoSlug: "polymarket",
    githubUrl: "https://github.com/Trading-GPT/Polymarket-trading-bot",
    sourceUrl: "https://github.com/Trading-GPT/Polymarket-trading-bot",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/Trading-GPT/Polymarket-trading-bot" },
      { label: "Polymarket", url: "https://polymarket.com" },
    ],
    gettingStartedLinks: [
      { label: "Repository README", url: "https://github.com/Trading-GPT/Polymarket-trading-bot#readme" },
    ],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "ai-trading-agent-demo"],
  }),
  recipe({
    slug: "intentkit-agent-cluster",
    name: "IntentKit Agent Cluster",
    description:
      "Self-hosted cloud agent cluster — collaborative AI agents with Web3 integrations, social tools, and extensible skills.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["ai", "infrastructure"],
    sourceType: "github",
    sourceLabel: "Crestal Network",
    ecosystems: ["Ethereum", "Base", "Solana"],
    apis: [
      { slug: "coinbase-agentkit", name: "Coinbase AgentKit" },
      { slug: "eliza", name: "Eliza" },
    ],
    techStack: ["Python", "AI Agents", "Docker", "Web3", "MIT"],
    logoSlug: "intentkit",
    githubUrl: "https://github.com/crestalnetwork/intentkit",
    sourceUrl: "https://github.com/crestalnetwork/intentkit",
    docsUrl: "https://intentcat.com/docs",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/crestalnetwork/intentkit" },
      { label: "Documentation", url: "https://intentcat.com/docs" },
    ],
    gettingStartedLinks: [
      { label: "Deployment Guide", url: "https://intentcat.com/docs" },
      { label: "Docker Compose", url: "https://github.com/crestalnetwork/intentkit/blob/main/docker-compose.yml" },
    ],
    relatedRecipeSlugs: ["agentkit", "onchain-agent-demo", "ai-trading-agent-demo"],
  }),
  recipe({
    slug: "solana-casino-games-evm",
    name: "Solana Casino Games (EVM)",
    description:
      "Multi-chain casino game templates for Solana and EVM — slots, roulette, and Web3 gaming flows from LaChance Lab.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["gaming", "trading"],
    sourceType: "github",
    sourceLabel: "LaChance Lab",
    ecosystems: ["Solana", "Ethereum", "Base"],
    apis: [
      { slug: "solana", name: "Solana" },
      { slug: "anchor", name: "Anchor" },
      { slug: "helius", name: "Helius" },
    ],
    techStack: ["Solana", "Anchor", "EVM", "TypeScript", "Casino Games"],
    logoSlug: "solana",
    githubUrl: "https://github.com/LaChance-Lab/solana-casino-games-evm-web3",
    sourceUrl: "https://github.com/LaChance-Lab/solana-casino-games-evm-web3",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/LaChance-Lab/solana-casino-games-evm-web3",
      },
    ],
    gettingStartedLinks: [
      {
        label: "Repository README",
        url: "https://github.com/LaChance-Lab/solana-casino-games-evm-web3#readme",
      },
    ],
    relatedRecipeSlugs: ["anchor-nextjs-counter", "solana-pay-store"],
  }),
  recipe({
    slug: "flow-telegram-quickstarts",
    name: "Flow Telegram Mini Apps",
    description:
      "Step-by-step courses for Telegram Web Apps on Flow — TWA auth, OKX wallet, Flow Cadence, and Privy EVM integration.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["wallets", "infrastructure"],
    sourceType: "tutorial",
    sourceLabel: "Flow",
    ecosystems: ["Ethereum", "Base"],
    apis: [
      { slug: "privy", name: "Privy" },
      { slug: "telegram", name: "Telegram" },
    ],
    techStack: ["Telegram Mini Apps", "Flow", "TypeScript", "TWA SDK", "Privy"],
    logoSlug: "flow",
    githubUrl: "https://github.com/onflow/telegram-integration-quickstarts",
    sourceUrl: "https://github.com/onflow/telegram-integration-quickstarts",
    docsUrl: "https://developers.flow.com",
    isOpenSource: true,
    isFree: true,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/onflow/telegram-integration-quickstarts",
      },
      { label: "Flow Docs", url: "https://developers.flow.com" },
    ],
    gettingStartedLinks: [
      {
        label: "Course 1: Deploy TWA",
        url: "https://github.com/onflow/telegram-integration-quickstarts/tree/main/Course_1_Deploy_A_Telegram_Web_App",
      },
      {
        label: "Course 5: Privy + Flow EVM",
        url: "https://github.com/onflow/telegram-integration-quickstarts/tree/main/Course_5_Connect_Privy_Wallet_Flow_EVM",
      },
    ],
    relatedRecipeSlugs: ["farcaster-mini-app-full-demo", "chatter-xmtp-privy"],
  }),
  recipe({
    slug: "hyper-alpha-arena",
    name: "Hyper Alpha Arena",
    description:
      "AI trading arena for Hyperliquid — multi-model agents compete with live perps data, portfolio tools, and a web dashboard.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "ai"],
    sourceType: "github",
    sourceLabel: "HammerGPT",
    ecosystems: ["Hyperliquid"],
    apis: [
      { slug: "hyperliquid", name: "Hyperliquid" },
      { slug: "pyth", name: "Pyth" },
      { slug: "telegram", name: "Telegram" },
    ],
    techStack: ["Python", "Hyperliquid API", "LLM Agents", "WebSocket"],
    logoSlug: "hyperliquid",
    githubUrl: "https://github.com/HammerGPT/Hyper-Alpha-Arena",
    sourceUrl: "https://github.com/HammerGPT/Hyper-Alpha-Arena",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/HammerGPT/Hyper-Alpha-Arena" },
      { label: "Hyperliquid Docs", url: "https://hyperliquid.gitbook.io/hyperliquid-docs" },
    ],
    gettingStartedLinks: [
      { label: "Repository README", url: "https://github.com/HammerGPT/Hyper-Alpha-Arena#readme" },
    ],
    relatedRecipeSlugs: ["hyperliquid-trading-bot", "crypto-trading-arena"],
  }),
  recipe({
    slug: "crypto-trading-arena",
    name: "Crypto Trading Arena",
    description:
      "Multi-agent crypto trading arena where LLM bots compete on live Coinbase or Binance data via Kafka and Calfkit orchestration.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "ai"],
    sourceType: "github",
    sourceLabel: "ryan-yuuu",
    ecosystems: ["Ethereum", "Base"],
    apis: [
      { slug: "pyth", name: "Pyth" },
      { slug: "telegram", name: "Telegram" },
    ],
    techStack: ["Python", "Kafka", "Calfkit", "Coinbase", "Binance", "LLM"],
    logoSlug: "coinbase",
    githubUrl: "https://github.com/ryan-yuuu/crypto-trading-arena",
    sourceUrl: "https://github.com/ryan-yuuu/crypto-trading-arena",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/ryan-yuuu/crypto-trading-arena" },
    ],
    gettingStartedLinks: [
      { label: "Quickstart", url: "https://github.com/ryan-yuuu/crypto-trading-arena#quickstart" },
    ],
    relatedRecipeSlugs: ["hyper-alpha-arena", "agent-trading-arena", "ai-trading-agent-demo"],
  }),
  recipe({
    slug: "agent-trading-arena",
    name: "Agent Trading Arena (Research)",
    description:
      "EMNLP 2025 / ICML 2026 research code for LLM trading agents — closed-loop markets, self-play, and DecoupledMarket quantitative reasoning.",
    difficulty: "advanced",
    setupTime: "weekend",
    categories: ["trading", "ai", "analytics"],
    sourceType: "github",
    sourceLabel: "MTMQuantAI",
    ecosystems: ["Ethereum"],
    apis: [
      { slug: "ollama", name: "Ollama" },
      { slug: "huggingface", name: "Hugging Face" },
    ],
    techStack: ["Python", "LLM Agents", "Self-Play", "Market Simulation"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/MTMQuantAI/Agent-Trading-Arena",
    sourceUrl: "https://github.com/MTMQuantAI/Agent-Trading-Arena",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/MTMQuantAI/Agent-Trading-Arena" },
      { label: "EMNLP Paper", url: "https://arxiv.org/abs/2410.02381" },
    ],
    gettingStartedLinks: [
      { label: "Agent Trading Arena", url: "https://github.com/MTMQuantAI/Agent-Trading-Arena/tree/main/Agent-Trading-Arena" },
      { label: "DecoupledMarket", url: "https://github.com/MTMQuantAI/Agent-Trading-Arena/tree/main/decoupledmarket" },
    ],
    relatedRecipeSlugs: ["crypto-trading-arena", "hyper-alpha-arena"],
  }),
  recipe({
    slug: "turbo-eth-web3-app",
    name: "TurboETH Web3 App Template",
    description:
      "Next.js Web3 starter with RainbowKit, SIWE, Wagmi CLI, Prisma, Tailwind, and shadcn/ui — batteries-included dapp scaffold.",
    difficulty: "beginner",
    setupTime: "1-hour",
    categories: ["wallets", "infrastructure"],
    sourceType: "template",
    sourceLabel: "turbo-eth",
    ecosystems: ["Ethereum", "Base", "Arbitrum"],
    apis: [
      { slug: "rainbowkit", name: "RainbowKit" },
      { slug: "walletconnect", name: "WalletConnect" },
    ],
    techStack: ["Next.js", "RainbowKit", "SIWE", "Wagmi", "Prisma", "Tailwind"],
    logoSlug: "rainbowkit",
    githubUrl: "https://github.com/turbo-eth/template-web3-app",
    sourceUrl: "https://github.com/turbo-eth/template-web3-app",
    docsUrl: "https://www.turboeth.xyz",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/turbo-eth/template-web3-app" },
      { label: "TurboETH", url: "https://www.turboeth.xyz" },
    ],
    gettingStartedLinks: [
      { label: "Getting Started", url: "https://github.com/turbo-eth/template-web3-app#readme" },
    ],
    relatedRecipeSlugs: ["chatter-xmtp-privy", "onchain-commerce-shop", "dapp-starter-jellydn"],
  }),
  recipe({
    slug: "web3-template-show",
    name: "Web3 Template Show",
    description:
      "Flutter cross-platform template for crypto storefronts — wallet connect, token gating, and digital product sales for creators.",
    difficulty: "intermediate",
    setupTime: "weekend",
    categories: ["wallets", "infrastructure"],
    sourceType: "template",
    sourceLabel: "lO-l192",
    ecosystems: ["Ethereum", "Polygon"],
    apis: [
      { slug: "walletconnect", name: "WalletConnect" },
      { slug: "privy", name: "Privy" },
    ],
    techStack: ["Flutter", "WalletConnect", "Token Gating", "Dart"],
    logoSlug: "walletconnect",
    githubUrl: "https://github.com/lO-l192/Web3TemplateShow",
    sourceUrl: "https://github.com/lO-l192/Web3TemplateShow",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/lO-l192/Web3TemplateShow" },
    ],
    gettingStartedLinks: [
      { label: "Flutter Getting Started", url: "https://github.com/lO-l192/Web3TemplateShow#readme" },
    ],
    relatedRecipeSlugs: ["turbo-eth-web3-app", "onchain-commerce-shop"],
  }),
  recipe({
    slug: "dapp-starter-jellydn",
    name: "Dapp Starter (jellydn)",
    description:
      "Opinionated Ethereum dapp template — React, Next.js, Hardhat, TypeChain, web3-react, OpenZeppelin, and daisyUI Tailwind.",
    difficulty: "intermediate",
    setupTime: "1-hour",
    categories: ["infrastructure", "wallets"],
    sourceType: "template",
    sourceLabel: "jellydn",
    ecosystems: ["Ethereum", "Base", "Arbitrum"],
    apis: [
      { slug: "openzeppelin", name: "OpenZeppelin" },
      { slug: "alchemy", name: "Alchemy" },
    ],
    techStack: ["Next.js", "Hardhat", "TypeChain", "web3-react", "OpenZeppelin"],
    logoSlug: "ethereum",
    githubUrl: "https://github.com/jellydn/dapp-starter",
    sourceUrl: "https://github.com/jellydn/dapp-starter",
    isOpenSource: true,
    isFree: true,
    links: [
      { label: "GitHub", url: "https://github.com/jellydn/dapp-starter" },
    ],
    gettingStartedLinks: [
      { label: "Quick Start", url: "https://github.com/jellydn/dapp-starter#readme" },
    ],
    relatedRecipeSlugs: ["turbo-eth-web3-app", "scaffold-eth-2"],
  }),
];
